export const MOMAMBO_COPY = {
  title: 'Momambo',
  subtitle: 'Percebe a tua banda. Cresce com ela.',
  sections: {
    performance: 'Performance',
    trending: 'O que está a dar',
    strength: 'A tua força',
    opportunities: 'Oportunidades',
    topPerformance: 'Top Performance',
  },
  labels: {
    views: 'Visualizações',
    newFollowers: 'Novos Wis',
    likes: 'Likes',
    comments: 'Comentários',
    shares: 'Partilhas',
    kumbuEarned: 'Kumbu ganhos',
    bestContentType: 'Melhor tipo de conteúdo',
    bestTime: 'Melhor hora para publicar',
    strongestCategory: 'Categoria mais forte',
    audienceBehavior: 'Comportamento da audiência',
    hotTopics: 'Tópicos quentes',
    activeConversations: 'Conversas ativas',
    popularCategories: 'Categorias populares',
    growingSignals: 'Sinais de crescimento',
    createRoda: 'Criar uma Roda',
    openLive: 'Abrir sessão Live',
    publishContent: 'Publicar conteúdo',
    createAcademia: 'Criar sessão Academia',
    monetize: 'Monetizar conteúdo',
    posts: 'Publicações',
    voices: 'Vozes',
    lives: 'Lives',
    academy: 'Academia',
    last7days: 'Últimos 7 dias',
    last30days: 'Últimos 30 dias',
  },
} as const;
