/** Exact UI copy strings for Academia da Banda */
export const ACADEMIA_COPY = {
  title: 'ACADEMIA DA BANDA',
  subtitle: 'Na Academia a banda cresce.',
  tabAll: 'Todas',
  tabFree: 'Gratuitas',
  tabPremium: 'Premium',
  createSession: 'Criar sessão',
  reserve: 'Reservar',
  enter: 'Entrar',
  close: 'Encerrar',
  feedbackTitle: 'Como foi esta Mentoria?',
  feedbackQuestion: 'Valeu a pena?',
  feedbackDismiss: 'Agora não',
  feedbackSubmit: 'Enviar',
  verificationWarning: 'Precisas de verificação para cobrar.',
  sessionEnded: 'Sessão terminada',
  reviewMentor: 'Avaliar mentor',
  liveNow: 'Ao vivo agora',
  scheduled: 'Agendada',
  ended: 'Terminada',
  mentors: 'Mentores',
  people: 'Pessoas',
  chat: 'Chat',
  liveVideoArea: 'LiveKit Video Area',
  format1on1: '1:1',
  formatGroup: 'Grupo',
  formatMasterclass: 'Masterclass',
  lateRegistration: 'Inscrição tardia (+10%)',
  registrationClosed: 'Inscrições encerradas',
  sessionEndedInfo: 'Esta sessão já terminou.',
} as const;
