-- AFROLOC pan-african reference data — 54 countries + level-1 divisions.
-- Source: afroloc-app/src/data/africa-admin.json (canonical). nivel1_type = per-country
-- nomenclature (provincia/estado/wilaya/condado…). Deep divisions (Angola mun/comuna)
-- are loaded separately from the canonical AFROLOC divisions DB.

insert into public.afroloc_countries (iso, name, nivel1_type, official_languages, spoken_languages) values
  ('DZ', 'Argélia', 'província (wilaya)', '{"Árabe","Tamazight"}', '{"Árabe argelino (Darija)","Cabila","Chaoui","Mozabita","Tamacheque","Francês"}'),
  ('AO', 'Angola', 'província', '{"Português"}', '{"Umbundu","Kimbundu","Kikongo","Chokwe","Nganguela","Kwanyama","Fiote","Luvale"}'),
  ('BJ', 'Benim', 'departamento', '{"Francês"}', '{"Fon","Yoruba","Bariba","Dendi","Adja","Mina"}'),
  ('BW', 'Botsuana', 'distrito', '{"Inglês","Setswana"}', '{"Setswana","Kalanga","Kgalagadi","Herero"}'),
  ('BF', 'Burquina Faso', 'região', '{"Francês"}', '{"Mooré","Dioula (Bambara)","Fula (Fulfulde)","Gourmanché"}'),
  ('BI', 'Burúndi', 'província', '{"Kirundi","Francês","Inglês"}', '{"Kirundi","Suaíli"}'),
  ('CV', 'Cabo Verde', 'concelho (município)', '{"Português"}', '{"Crioulo cabo-verdiano (Kriolu)"}'),
  ('CM', 'Camarões', 'região', '{"Francês","Inglês"}', '{"Fula","Ewondo","Duala","Bamileke","Pidgin camaronês"}'),
  ('CF', 'República Centro-Africana', 'prefeitura', '{"Francês","Sango"}', '{"Sango","Gbaya","Banda"}'),
  ('TD', 'Chade', 'província', '{"Francês","Árabe"}', '{"Árabe chadiano","Sara","Kanembu","Maba"}'),
  ('KM', 'Comores', 'ilha', '{"Comoriano","Árabe","Francês"}', '{"Shikomori"}'),
  ('CG', 'Congo', 'departamento', '{"Francês"}', '{"Lingala","Kituba (Munukutuba)","Kongo"}'),
  ('CD', 'RD Congo', 'província', '{"Francês"}', '{"Lingala","Suaíli","Kikongo","Tshiluba"}'),
  ('CI', 'Costa do Marfim', 'distrito', '{"Francês"}', '{"Dioula","Baoulé","Bété","Senufo","Agni"}'),
  ('DJ', 'Djibuti', 'região', '{"Francês","Árabe"}', '{"Somali","Afar","Árabe"}'),
  ('EG', 'Egito', 'governadoria', '{"Árabe"}', '{"Árabe egípcio","Copta (litúrgico)","Núbio","Beja","Siwi"}'),
  ('GQ', 'Guiné Equatorial', 'província', '{"Espanhol","Francês","Português"}', '{"Fang","Bubi","Pidgin inglês (Pichinglis)"}'),
  ('ER', 'Eritreia', 'região (zoba)', '{"Tigrínia","Árabe","Inglês"}', '{"Tigrínia","Tigré","Afar","Saho","Bilen","Kunama"}'),
  ('SZ', 'Essuatíni', 'região', '{"SiSwati","Inglês"}', '{"SiSwati","Zulu"}'),
  ('ET', 'Etiópia', 'estado regional', '{"Amárico (federal)"}', '{"Oromo","Amárico","Somali","Tigrínia","Sidama","Wolaita"}'),
  ('GA', 'Gabão', 'província', '{"Francês"}', '{"Fang","Myènè","Punu","Nzebi"}'),
  ('GM', 'Gâmbia', 'área de governo local', '{"Inglês"}', '{"Mandinga","Wolof","Fula","Jola","Serer"}'),
  ('GH', 'Gana', 'região', '{"Inglês"}', '{"Akan (Twi/Fante)","Ewe","Ga","Dagbani","Hausa"}'),
  ('GN', 'Guiné', 'região', '{"Francês"}', '{"Pular (Fula)","Maninka (Malinké)","Susu"}'),
  ('GW', 'Guiné-Bissau', 'região', '{"Português"}', '{"Crioulo da Guiné-Bissau (Kriol)","Balanta","Fula","Mandinga","Manjaco"}'),
  ('KE', 'Quénia', 'condado', '{"Inglês","Suaíli"}', '{"Kikuyu","Luhya","Luo","Kalenjin","Kamba","Suaíli"}'),
  ('LS', 'Lesoto', 'distrito', '{"Sesotho","Inglês"}', '{"Sesotho","Zulu","Xhosa"}'),
  ('LR', 'Libéria', 'condado', '{"Inglês"}', '{"Kpelle","Bassa","Inglês liberiano (Kreyol)","Grebo","Mano"}'),
  ('LY', 'Líbia', 'distrito (shabiyah)', '{"Árabe"}', '{"Árabe líbio","Berbere (Nafusi)","Tamacheque"}'),
  ('MG', 'Madagáscar', 'região', '{"Malgaxe","Francês"}', '{"Malgaxe (dialetos)"}'),
  ('MW', 'Maláui', 'distrito', '{"Inglês","Chichewa"}', '{"Chichewa","Chitumbuka","Yao","Lomwe"}'),
  ('ML', 'Mali', 'região', '{"Bambara (e outras nacionais)"}', '{"Bambara","Fula","Songhai","Tamacheque","Soninké","Francês"}'),
  ('MR', 'Mauritânia', 'região (wilaya)', '{"Árabe"}', '{"Árabe hassaniya","Pulaar","Soninké","Wolof"}'),
  ('MU', 'Maurícia', 'distrito', '{"Inglês","Francês"}', '{"Crioulo mauriciano","Francês","Bhojpuri"}'),
  ('MA', 'Marrocos', 'região', '{"Árabe","Amazigh"}', '{"Árabe marroquino (Darija)","Tachelhit","Tarifit","Tamazight central","Francês"}'),
  ('MZ', 'Moçambique', 'província', '{"Português"}', '{"Makhuwa","Changana (Tsonga)","Sena","Lomwe","Ndau","Tshwa"}'),
  ('NA', 'Namíbia', 'região', '{"Inglês"}', '{"Oshiwambo","Khoekhoe (Nama/Damara)","Afrikaans","Otjiherero","RuKavango"}'),
  ('NE', 'Níger', 'região', '{"Francês (e línguas nacionais)"}', '{"Hausa","Zarma-Songhai","Fula","Tamacheque","Kanuri"}'),
  ('NG', 'Nigéria', 'estado', '{"Inglês"}', '{"Hausa","Yoruba","Igbo","Pidgin nigeriano","Fula"}'),
  ('RW', 'Ruanda', 'província', '{"Kinyarwanda","Inglês","Francês","Suaíli"}', '{"Kinyarwanda"}'),
  ('ST', 'São Tomé e Príncipe', 'distrito', '{"Português"}', '{"Forro","Angolar","Principense"}'),
  ('SN', 'Senegal', 'região', '{"Francês"}', '{"Wolof","Pulaar","Serer","Mandinga","Soninké","Diola"}'),
  ('SC', 'Seicheles', 'distrito', '{"Crioulo seichelense","Inglês","Francês"}', '{"Crioulo seichelense (Seselwa)"}'),
  ('SL', 'Serra Leoa', 'província', '{"Inglês"}', '{"Krio","Mende","Temne","Limba"}'),
  ('SO', 'Somália', 'região', '{"Somali","Árabe"}', '{"Somali","Maay","Árabe"}'),
  ('ZA', 'África do Sul', 'província', '{"Zulu","Xhosa","Afrikaans","Inglês","Sepedi","Setswana","Sesotho","Xitsonga","SiSwati","Tshivenda","isiNdebele","Língua Gestual SA"}', '{"Zulu","Xhosa","Afrikaans","Inglês","Sepedi"}'),
  ('SS', 'Sudão do Sul', 'estado', '{"Inglês"}', '{"Dinka","Nuer","Bari","Zande","Árabe de Juba","Shilluk"}'),
  ('SD', 'Sudão', 'estado', '{"Árabe","Inglês"}', '{"Árabe sudanês","Beja","Núbio","Fur"}'),
  ('TZ', 'Tanzânia', 'região', '{"Suaíli"}', '{"Suaíli","Sukuma","Chagga","Nyamwezi","Haya"}'),
  ('TG', 'Togo', 'região', '{"Francês"}', '{"Ewe","Kabiyè","Mina","Tem"}'),
  ('TN', 'Tunísia', 'governadoria', '{"Árabe"}', '{"Árabe tunisino (Derja)","Francês","Berbere"}'),
  ('UG', 'Uganda', 'região', '{"Inglês","Suaíli"}', '{"Luganda","Suaíli","Runyankole","Acholi","Lango"}'),
  ('ZM', 'Zâmbia', 'província', '{"Inglês"}', '{"Bemba","Nyanja","Tonga","Lozi","Lunda","Kaonde","Luvale"}'),
  ('ZW', 'Zimbábue', 'província', '{"Shona","Ndebele","Inglês (e 13 outras)"}', '{"Shona","Ndebele","Inglês"}')
on conflict (iso) do update set name=excluded.name, nivel1_type=excluded.nivel1_type, official_languages=excluded.official_languages, spoken_languages=excluded.spoken_languages;

insert into public.administrative_divisions (country_code, level, code, name, name_norm, parent_code, parent_level) values
  ('DZ', 1, 'DZ-ADR', 'Adrar', 'adrar', null, null),
  ('DZ', 1, 'DZ-CHL', 'Chlef', 'chlef', null, null),
  ('DZ', 1, 'DZ-LAG', 'Laghouat', 'laghouat', null, null),
  ('DZ', 1, 'DZ-OUM', 'Oum El Bouaghi', 'oum el bouaghi', null, null),
  ('DZ', 1, 'DZ-BAT', 'Batna', 'batna', null, null),
  ('DZ', 1, 'DZ-BEJ', 'Béjaïa', 'bejaia', null, null),
  ('DZ', 1, 'DZ-BIS', 'Biskra', 'biskra', null, null),
  ('DZ', 1, 'DZ-BEC', 'Béchar', 'bechar', null, null),
  ('DZ', 1, 'DZ-BLI', 'Blida', 'blida', null, null),
  ('DZ', 1, 'DZ-BOU', 'Bouira', 'bouira', null, null),
  ('DZ', 1, 'DZ-TAM', 'Tamanrasset', 'tamanrasset', null, null),
  ('DZ', 1, 'DZ-TEB', 'Tébessa', 'tebessa', null, null),
  ('DZ', 1, 'DZ-TLE', 'Tlemcen', 'tlemcen', null, null),
  ('DZ', 1, 'DZ-TIA', 'Tiaret', 'tiaret', null, null),
  ('DZ', 1, 'DZ-TIZ', 'Tizi Ouzou', 'tizi ouzou', null, null),
  ('DZ', 1, 'DZ-ARG', 'Argel', 'argel', null, null),
  ('DZ', 1, 'DZ-DJE', 'Djelfa', 'djelfa', null, null),
  ('DZ', 1, 'DZ-JIJ', 'Jijel', 'jijel', null, null),
  ('DZ', 1, 'DZ-SET', 'Sétif', 'setif', null, null),
  ('DZ', 1, 'DZ-SAI', 'Saïda', 'saida', null, null),
  ('DZ', 1, 'DZ-SKI', 'Skikda', 'skikda', null, null),
  ('DZ', 1, 'DZ-SID', 'Sidi Bel Abbès', 'sidi bel abbes', null, null),
  ('DZ', 1, 'DZ-ANN', 'Annaba', 'annaba', null, null),
  ('DZ', 1, 'DZ-GUE', 'Guelma', 'guelma', null, null),
  ('DZ', 1, 'DZ-CON', 'Constantine', 'constantine', null, null),
  ('DZ', 1, 'DZ-MED', 'Médéa', 'medea', null, null),
  ('DZ', 1, 'DZ-MOS', 'Mostaganem', 'mostaganem', null, null),
  ('DZ', 1, 'DZ-MSI', 'M''Sila', 'm''sila', null, null),
  ('DZ', 1, 'DZ-MAS', 'Mascara', 'mascara', null, null),
  ('DZ', 1, 'DZ-OUA', 'Ouargla', 'ouargla', null, null),
  ('DZ', 1, 'DZ-ORA', 'Oran', 'oran', null, null),
  ('DZ', 1, 'DZ-ELB', 'El Bayadh', 'el bayadh', null, null),
  ('DZ', 1, 'DZ-ILL', 'Illizi', 'illizi', null, null),
  ('DZ', 1, 'DZ-BOR', 'Bordj Bou Arréridj', 'bordj bou arreridj', null, null),
  ('DZ', 1, 'DZ-BOUM', 'Boumerdès', 'boumerdes', null, null),
  ('DZ', 1, 'DZ-ELT', 'El Tarf', 'el tarf', null, null),
  ('DZ', 1, 'DZ-TIN', 'Tindouf', 'tindouf', null, null),
  ('DZ', 1, 'DZ-TIS', 'Tissemsilt', 'tissemsilt', null, null),
  ('DZ', 1, 'DZ-ELO', 'El Oued', 'el oued', null, null),
  ('DZ', 1, 'DZ-KHE', 'Khenchela', 'khenchela', null, null),
  ('DZ', 1, 'DZ-SOU', 'Souk Ahras', 'souk ahras', null, null),
  ('DZ', 1, 'DZ-TIP', 'Tipaza', 'tipaza', null, null),
  ('DZ', 1, 'DZ-MIL', 'Mila', 'mila', null, null),
  ('DZ', 1, 'DZ-AIN', 'Aïn Defla', 'ain defla', null, null),
  ('DZ', 1, 'DZ-NAA', 'Naâma', 'naama', null, null),
  ('DZ', 1, 'DZ-AINT', 'Aïn Témouchent', 'ain temouchent', null, null),
  ('DZ', 1, 'DZ-GHA', 'Ghardaïa', 'ghardaia', null, null),
  ('DZ', 1, 'DZ-REL', 'Relizane', 'relizane', null, null),
  ('DZ', 1, 'DZ-TIM', 'Timimoun', 'timimoun', null, null),
  ('DZ', 1, 'DZ-BORD', 'Bordj Badji Mokhtar', 'bordj badji mokhtar', null, null),
  ('DZ', 1, 'DZ-OUL', 'Ouled Djellal', 'ouled djellal', null, null),
  ('DZ', 1, 'DZ-BEN', 'Béni Abbès', 'beni abbes', null, null),
  ('DZ', 1, 'DZ-INS', 'In Salah', 'in salah', null, null),
  ('DZ', 1, 'DZ-ING', 'In Guezzam', 'in guezzam', null, null),
  ('DZ', 1, 'DZ-TOU', 'Touggourt', 'touggourt', null, null),
  ('DZ', 1, 'DZ-DJA', 'Djanet', 'djanet', null, null),
  ('DZ', 1, 'DZ-ELM', 'El M''Ghair', 'el m''ghair', null, null),
  ('DZ', 1, 'DZ-ELME', 'El Meniaa', 'el meniaa', null, null),
  ('BJ', 1, 'BJ-ALI', 'Alibori', 'alibori', null, null),
  ('BJ', 1, 'BJ-ATA', 'Atacora', 'atacora', null, null),
  ('BJ', 1, 'BJ-ATL', 'Atlantique', 'atlantique', null, null),
  ('BJ', 1, 'BJ-BOR', 'Borgou', 'borgou', null, null),
  ('BJ', 1, 'BJ-COL', 'Collines', 'collines', null, null),
  ('BJ', 1, 'BJ-COU', 'Couffo', 'couffo', null, null),
  ('BJ', 1, 'BJ-DON', 'Donga', 'donga', null, null),
  ('BJ', 1, 'BJ-LIT', 'Littoral', 'littoral', null, null),
  ('BJ', 1, 'BJ-MON', 'Mono', 'mono', null, null),
  ('BJ', 1, 'BJ-OUE', 'Ouémé', 'oueme', null, null),
  ('BJ', 1, 'BJ-PLA', 'Plateau', 'plateau', null, null),
  ('BJ', 1, 'BJ-ZOU', 'Zou', 'zou', null, null),
  ('BW', 1, 'BW-CEN', 'Central', 'central', null, null),
  ('BW', 1, 'BW-GHA', 'Ghanzi', 'ghanzi', null, null),
  ('BW', 1, 'BW-KGA', 'Kgalagadi', 'kgalagadi', null, null),
  ('BW', 1, 'BW-KGAT', 'Kgatleng', 'kgatleng', null, null),
  ('BW', 1, 'BW-KWE', 'Kweneng', 'kweneng', null, null),
  ('BW', 1, 'BW-NOR', 'North-East', 'north-east', null, null),
  ('BW', 1, 'BW-NORT', 'North-West', 'north-west', null, null),
  ('BW', 1, 'BW-SOU', 'South-East', 'south-east', null, null),
  ('BW', 1, 'BW-SOUT', 'Southern', 'southern', null, null),
  ('BW', 1, 'BW-CHO', 'Chobe', 'chobe', null, null),
  ('BF', 1, 'BF-BOU', 'Boucle du Mouhoun', 'boucle du mouhoun', null, null),
  ('BF', 1, 'BF-CAS', 'Cascades', 'cascades', null, null),
  ('BF', 1, 'BF-CEN', 'Centre', 'centre', null, null),
  ('BF', 1, 'BF-CENT', 'Centre-Est', 'centre-est', null, null),
  ('BF', 1, 'BF-CET', 'Centre-Nord', 'centre-nord', null, null),
  ('BF', 1, 'BF-CER', 'Centre-Ouest', 'centre-ouest', null, null),
  ('BF', 1, 'BF-CEE', 'Centre-Sud', 'centre-sud', null, null),
  ('BF', 1, 'BF-EST', 'Est', 'est', null, null),
  ('BF', 1, 'BF-HAU', 'Hauts-Bassins', 'hauts-bassins', null, null),
  ('BF', 1, 'BF-NOR', 'Nord', 'nord', null, null),
  ('BF', 1, 'BF-PLA', 'Plateau-Central', 'plateau-central', null, null),
  ('BF', 1, 'BF-SAH', 'Sahel', 'sahel', null, null),
  ('BF', 1, 'BF-SUD', 'Sud-Ouest', 'sud-ouest', null, null),
  ('BI', 1, 'BI-BUB', 'Bubanza', 'bubanza', null, null),
  ('BI', 1, 'BI-BUJ', 'Bujumbura Mairie', 'bujumbura mairie', null, null),
  ('BI', 1, 'BI-BUJU', 'Bujumbura Rural', 'bujumbura rural', null, null),
  ('BI', 1, 'BI-BUR', 'Bururi', 'bururi', null, null),
  ('BI', 1, 'BI-CAN', 'Cankuzo', 'cankuzo', null, null),
  ('BI', 1, 'BI-CIB', 'Cibitoke', 'cibitoke', null, null),
  ('BI', 1, 'BI-GIT', 'Gitega', 'gitega', null, null),
  ('BI', 1, 'BI-KAR', 'Karuzi', 'karuzi', null, null),
  ('BI', 1, 'BI-KAY', 'Kayanza', 'kayanza', null, null),
  ('BI', 1, 'BI-KIR', 'Kirundo', 'kirundo', null, null),
  ('BI', 1, 'BI-MAK', 'Makamba', 'makamba', null, null),
  ('BI', 1, 'BI-MUR', 'Muramvya', 'muramvya', null, null),
  ('BI', 1, 'BI-MUY', 'Muyinga', 'muyinga', null, null),
  ('BI', 1, 'BI-MWA', 'Mwaro', 'mwaro', null, null),
  ('BI', 1, 'BI-NGO', 'Ngozi', 'ngozi', null, null),
  ('BI', 1, 'BI-RUM', 'Rumonge', 'rumonge', null, null),
  ('BI', 1, 'BI-RUT', 'Rutana', 'rutana', null, null),
  ('BI', 1, 'BI-RUY', 'Ruyigi', 'ruyigi', null, null),
  ('CV', 1, 'CV-BOA', 'Boa Vista', 'boa vista', null, null),
  ('CV', 1, 'CV-BRA', 'Brava', 'brava', null, null),
  ('CV', 1, 'CV-MAI', 'Maio', 'maio', null, null),
  ('CV', 1, 'CV-MOS', 'Mosteiros', 'mosteiros', null, null),
  ('CV', 1, 'CV-PAU', 'Paul', 'paul', null, null),
  ('CV', 1, 'CV-POR', 'Porto Novo', 'porto novo', null, null),
  ('CV', 1, 'CV-PRA', 'Praia', 'praia', null, null),
  ('CV', 1, 'CV-RIB', 'Ribeira Brava', 'ribeira brava', null, null),
  ('CV', 1, 'CV-RIBE', 'Ribeira Grande', 'ribeira grande', null, null),
  ('CV', 1, 'CV-RIE', 'Ribeira Grande de Santiago', 'ribeira grande de santiago', null, null),
  ('CV', 1, 'CV-SAL', 'Sal', 'sal', null, null),
  ('CV', 1, 'CV-SAN', 'Santa Catarina', 'santa catarina', null, null),
  ('CV', 1, 'CV-SANT', 'Santa Catarina do Fogo', 'santa catarina do fogo', null, null),
  ('CV', 1, 'CV-SAT', 'Santa Cruz', 'santa cruz', null, null),
  ('CV', 1, 'CV-SAO', 'São Domingos', 'sao domingos', null, null),
  ('CV', 1, 'CV-SAOF', 'São Filipe', 'sao filipe', null, null),
  ('CV', 1, 'CV-SAOL', 'São Lourenço dos Órgãos', 'sao lourenco dos orgaos', null, null),
  ('CV', 1, 'CV-SAOM', 'São Miguel', 'sao miguel', null, null),
  ('CV', 1, 'CV-SAOS', 'São Salvador do Mundo', 'sao salvador do mundo', null, null),
  ('CV', 1, 'CV-SAOV', 'São Vicente', 'sao vicente', null, null),
  ('CV', 1, 'CV-TAR', 'Tarrafal', 'tarrafal', null, null),
  ('CV', 1, 'CV-TARR', 'Tarrafal de São Nicolau', 'tarrafal de sao nicolau', null, null),
  ('CM', 1, 'CM-ADA', 'Adamaoua', 'adamaoua', null, null),
  ('CM', 1, 'CM-CEN', 'Centre', 'centre', null, null),
  ('CM', 1, 'CM-EST', 'Est', 'est', null, null),
  ('CM', 1, 'CM-EXT', 'Extrême-Nord', 'extreme-nord', null, null),
  ('CM', 1, 'CM-LIT', 'Littoral', 'littoral', null, null),
  ('CM', 1, 'CM-NOR', 'Nord', 'nord', null, null),
  ('CM', 1, 'CM-NORD', 'Nord-Ouest', 'nord-ouest', null, null),
  ('CM', 1, 'CM-OUE', 'Ouest', 'ouest', null, null),
  ('CM', 1, 'CM-SUD', 'Sud', 'sud', null, null),
  ('CM', 1, 'CM-SUDO', 'Sud-Ouest', 'sud-ouest', null, null),
  ('CF', 1, 'CF-BAM', 'Bamingui-Bangoran', 'bamingui-bangoran', null, null),
  ('CF', 1, 'CF-BAN', 'Bangui', 'bangui', null, null),
  ('CF', 1, 'CF-BAS', 'Basse-Kotto', 'basse-kotto', null, null),
  ('CF', 1, 'CF-HAU', 'Haute-Kotto', 'haute-kotto', null, null),
  ('CF', 1, 'CF-HAUT', 'Haut-Mbomou', 'haut-mbomou', null, null),
  ('CF', 1, 'CF-KEM', 'Kémo', 'kemo', null, null),
  ('CF', 1, 'CF-LOB', 'Lobaye', 'lobaye', null, null),
  ('CF', 1, 'CF-MAM', 'Mambéré-Kadéï', 'mambere-kadei', null, null),
  ('CF', 1, 'CF-MBO', 'Mbomou', 'mbomou', null, null),
  ('CF', 1, 'CF-NAN', 'Nana-Grébizi', 'nana-grebizi', null, null),
  ('CF', 1, 'CF-NANA', 'Nana-Mambéré', 'nana-mambere', null, null),
  ('CF', 1, 'CF-OMB', 'Ombella-M''Poko', 'ombella-m''poko', null, null),
  ('CF', 1, 'CF-OUA', 'Ouaka', 'ouaka', null, null),
  ('CF', 1, 'CF-OUH', 'Ouham', 'ouham', null, null),
  ('CF', 1, 'CF-OUHA', 'Ouham-Pendé', 'ouham-pende', null, null),
  ('CF', 1, 'CF-SAN', 'Sangha-Mbaéré', 'sangha-mbaere', null, null),
  ('CF', 1, 'CF-VAK', 'Vakaga', 'vakaga', null, null),
  ('TD', 1, 'TD-BAT', 'Batha', 'batha', null, null),
  ('TD', 1, 'TD-BOR', 'Borkou', 'borkou', null, null),
  ('TD', 1, 'TD-CHA', 'Chari-Baguirmi', 'chari-baguirmi', null, null),
  ('TD', 1, 'TD-ENN', 'Ennedi-Est', 'ennedi-est', null, null),
  ('TD', 1, 'TD-ENNE', 'Ennedi-Ouest', 'ennedi-ouest', null, null),
  ('TD', 1, 'TD-GUE', 'Guéra', 'guera', null, null),
  ('TD', 1, 'TD-HAD', 'Hadjer-Lamis', 'hadjer-lamis', null, null),
  ('TD', 1, 'TD-KAN', 'Kanem', 'kanem', null, null),
  ('TD', 1, 'TD-LAC', 'Lac', 'lac', null, null),
  ('TD', 1, 'TD-LOG', 'Logone Occidental', 'logone occidental', null, null),
  ('TD', 1, 'TD-LOGO', 'Logone Oriental', 'logone oriental', null, null),
  ('TD', 1, 'TD-MAN', 'Mandoul', 'mandoul', null, null),
  ('TD', 1, 'TD-MAY', 'Mayo-Kebbi Est', 'mayo-kebbi est', null, null),
  ('TD', 1, 'TD-MAYO', 'Mayo-Kebbi Ouest', 'mayo-kebbi ouest', null, null),
  ('TD', 1, 'TD-MOY', 'Moyen-Chari', 'moyen-chari', null, null),
  ('TD', 1, 'TD-OUA', 'Ouaddaï', 'ouaddai', null, null),
  ('TD', 1, 'TD-SAL', 'Salamat', 'salamat', null, null),
  ('TD', 1, 'TD-SIL', 'Sila', 'sila', null, null),
  ('TD', 1, 'TD-TAN', 'Tandjilé', 'tandjile', null, null),
  ('TD', 1, 'TD-TIB', 'Tibesti', 'tibesti', null, null),
  ('TD', 1, 'TD-NDJ', 'N''Djamena', 'n''djamena', null, null),
  ('TD', 1, 'TD-WAD', 'Wadi Fira', 'wadi fira', null, null),
  ('TD', 1, 'TD-BAR', 'Barh-El-Gazel', 'barh-el-gazel', null, null),
  ('KM', 1, 'KM-GRA', 'Grande Comore (Ngazidja)', 'grande comore (ngazidja)', null, null),
  ('KM', 1, 'KM-ANJ', 'Anjouan (Ndzuwani)', 'anjouan (ndzuwani)', null, null),
  ('KM', 1, 'KM-MOH', 'Mohéli (Mwali)', 'moheli (mwali)', null, null),
  ('CG', 1, 'CG-BOU', 'Bouenza', 'bouenza', null, null),
  ('CG', 1, 'CG-BRA', 'Brazzaville', 'brazzaville', null, null),
  ('CG', 1, 'CG-CUV', 'Cuvette', 'cuvette', null, null),
  ('CG', 1, 'CG-CUVE', 'Cuvette-Ouest', 'cuvette-ouest', null, null),
  ('CG', 1, 'CG-KOU', 'Kouilou', 'kouilou', null, null),
  ('CG', 1, 'CG-LEK', 'Lékoumou', 'lekoumou', null, null),
  ('CG', 1, 'CG-LIK', 'Likouala', 'likouala', null, null),
  ('CG', 1, 'CG-NIA', 'Niari', 'niari', null, null),
  ('CG', 1, 'CG-PLA', 'Plateaux', 'plateaux', null, null),
  ('CG', 1, 'CG-POI', 'Pointe-Noire', 'pointe-noire', null, null),
  ('CG', 1, 'CG-POO', 'Pool', 'pool', null, null),
  ('CG', 1, 'CG-SAN', 'Sangha', 'sangha', null, null),
  ('CD', 1, 'CD-BAS', 'Bas-Uélé', 'bas-uele', null, null),
  ('CD', 1, 'CD-EQU', 'Équateur', 'equateur', null, null),
  ('CD', 1, 'CD-HAU', 'Haut-Katanga', 'haut-katanga', null, null),
  ('CD', 1, 'CD-HAUT', 'Haut-Lomami', 'haut-lomami', null, null),
  ('CD', 1, 'CD-HAT', 'Haut-Uélé', 'haut-uele', null, null),
  ('CD', 1, 'CD-ITU', 'Ituri', 'ituri', null, null),
  ('CD', 1, 'CD-KAS', 'Kasaï', 'kasai', null, null),
  ('CD', 1, 'CD-KASA', 'Kasaï-Central', 'kasai-central', null, null),
  ('CD', 1, 'CD-KAA', 'Kasaï-Oriental', 'kasai-oriental', null, null),
  ('CD', 1, 'CD-KIN', 'Kinshasa', 'kinshasa', null, null),
  ('CD', 1, 'CD-KON', 'Kongo Central', 'kongo central', null, null),
  ('CD', 1, 'CD-KWA', 'Kwango', 'kwango', null, null),
  ('CD', 1, 'CD-KWI', 'Kwilu', 'kwilu', null, null),
  ('CD', 1, 'CD-LOM', 'Lomami', 'lomami', null, null),
  ('CD', 1, 'CD-LUA', 'Lualaba', 'lualaba', null, null),
  ('CD', 1, 'CD-MAI', 'Mai-Ndombe', 'mai-ndombe', null, null),
  ('CD', 1, 'CD-MAN', 'Maniema', 'maniema', null, null),
  ('CD', 1, 'CD-MON', 'Mongala', 'mongala', null, null),
  ('CD', 1, 'CD-NOR', 'Nord-Kivu', 'nord-kivu', null, null),
  ('CD', 1, 'CD-NORD', 'Nord-Ubangi', 'nord-ubangi', null, null),
  ('CD', 1, 'CD-SAN', 'Sankuru', 'sankuru', null, null),
  ('CD', 1, 'CD-SUD', 'Sud-Kivu', 'sud-kivu', null, null),
  ('CD', 1, 'CD-SUDU', 'Sud-Ubangi', 'sud-ubangi', null, null),
  ('CD', 1, 'CD-TAN', 'Tanganyika', 'tanganyika', null, null),
  ('CD', 1, 'CD-TSH', 'Tshopo', 'tshopo', null, null),
  ('CD', 1, 'CD-TSHU', 'Tshuapa', 'tshuapa', null, null),
  ('CI', 1, 'CI-ABI', 'Abidjan', 'abidjan', null, null),
  ('CI', 1, 'CI-BAS', 'Bas-Sassandra', 'bas-sassandra', null, null),
  ('CI', 1, 'CI-COM', 'Comoé', 'comoe', null, null),
  ('CI', 1, 'CI-DEN', 'Denguélé', 'denguele', null, null),
  ('CI', 1, 'CI-GOH', 'Gôh-Djiboua', 'goh-djiboua', null, null),
  ('CI', 1, 'CI-LAC', 'Lacs', 'lacs', null, null),
  ('CI', 1, 'CI-LAG', 'Lagunes', 'lagunes', null, null),
  ('CI', 1, 'CI-MON', 'Montagnes', 'montagnes', null, null),
  ('CI', 1, 'CI-SAS', 'Sassandra-Marahoué', 'sassandra-marahoue', null, null),
  ('CI', 1, 'CI-SAV', 'Savanes', 'savanes', null, null),
  ('CI', 1, 'CI-VAL', 'Vallée du Bandama', 'vallee du bandama', null, null),
  ('CI', 1, 'CI-WOR', 'Woroba', 'woroba', null, null),
  ('CI', 1, 'CI-YAM', 'Yamoussoukro', 'yamoussoukro', null, null),
  ('CI', 1, 'CI-ZAN', 'Zanzan', 'zanzan', null, null),
  ('DJ', 1, 'DJ-ALI', 'Ali Sabieh', 'ali sabieh', null, null),
  ('DJ', 1, 'DJ-ART', 'Arta', 'arta', null, null),
  ('DJ', 1, 'DJ-DIK', 'Dikhil', 'dikhil', null, null),
  ('DJ', 1, 'DJ-DJI', 'Djibouti', 'djibouti', null, null),
  ('DJ', 1, 'DJ-OBO', 'Obock', 'obock', null, null),
  ('DJ', 1, 'DJ-TAD', 'Tadjourah', 'tadjourah', null, null),
  ('EG', 1, 'EG-ALE', 'Alexandria', 'alexandria', null, null),
  ('EG', 1, 'EG-ASW', 'Aswan', 'aswan', null, null),
  ('EG', 1, 'EG-ASY', 'Asyut', 'asyut', null, null),
  ('EG', 1, 'EG-BEH', 'Beheira', 'beheira', null, null),
  ('EG', 1, 'EG-BEN', 'Beni Suef', 'beni suef', null, null),
  ('EG', 1, 'EG-CAI', 'Cairo', 'cairo', null, null),
  ('EG', 1, 'EG-DAK', 'Dakahlia', 'dakahlia', null, null),
  ('EG', 1, 'EG-DAM', 'Damietta', 'damietta', null, null),
  ('EG', 1, 'EG-FAI', 'Faiyum', 'faiyum', null, null),
  ('EG', 1, 'EG-GHA', 'Gharbia', 'gharbia', null, null),
  ('EG', 1, 'EG-GIZ', 'Giza', 'giza', null, null),
  ('EG', 1, 'EG-ISM', 'Ismailia', 'ismailia', null, null),
  ('EG', 1, 'EG-KAF', 'Kafr El Sheikh', 'kafr el sheikh', null, null),
  ('EG', 1, 'EG-LUX', 'Luxor', 'luxor', null, null),
  ('EG', 1, 'EG-MAT', 'Matrouh', 'matrouh', null, null),
  ('EG', 1, 'EG-MIN', 'Minya', 'minya', null, null),
  ('EG', 1, 'EG-MON', 'Monufia', 'monufia', null, null),
  ('EG', 1, 'EG-NEW', 'New Valley', 'new valley', null, null),
  ('EG', 1, 'EG-NOR', 'North Sinai', 'north sinai', null, null),
  ('EG', 1, 'EG-POR', 'Port Said', 'port said', null, null),
  ('EG', 1, 'EG-QAL', 'Qalyubia', 'qalyubia', null, null),
  ('EG', 1, 'EG-QEN', 'Qena', 'qena', null, null),
  ('EG', 1, 'EG-RED', 'Red Sea', 'red sea', null, null),
  ('EG', 1, 'EG-SHA', 'Sharqia', 'sharqia', null, null),
  ('EG', 1, 'EG-SOH', 'Sohag', 'sohag', null, null),
  ('EG', 1, 'EG-SOU', 'South Sinai', 'south sinai', null, null),
  ('EG', 1, 'EG-SUE', 'Suez', 'suez', null, null),
  ('GQ', 1, 'GQ-ANN', 'Annobón', 'annobon', null, null),
  ('GQ', 1, 'GQ-BIO', 'Bioko Norte', 'bioko norte', null, null),
  ('GQ', 1, 'GQ-BIOK', 'Bioko Sur', 'bioko sur', null, null),
  ('GQ', 1, 'GQ-CEN', 'Centro Sur', 'centro sur', null, null),
  ('GQ', 1, 'GQ-DJI', 'Djibloho', 'djibloho', null, null),
  ('GQ', 1, 'GQ-KIE', 'Kié-Ntem', 'kie-ntem', null, null),
  ('GQ', 1, 'GQ-LIT', 'Litoral', 'litoral', null, null),
  ('GQ', 1, 'GQ-WEL', 'Wele-Nzas', 'wele-nzas', null, null),
  ('ER', 1, 'ER-ANS', 'Anseba', 'anseba', null, null),
  ('ER', 1, 'ER-DEB', 'Debub', 'debub', null, null),
  ('ER', 1, 'ER-GAS', 'Gash-Barka', 'gash-barka', null, null),
  ('ER', 1, 'ER-MAE', 'Maekel', 'maekel', null, null),
  ('ER', 1, 'ER-NOR', 'Northern Red Sea', 'northern red sea', null, null),
  ('ER', 1, 'ER-SOU', 'Southern Red Sea', 'southern red sea', null, null),
  ('SZ', 1, 'SZ-HHO', 'Hhohho', 'hhohho', null, null),
  ('SZ', 1, 'SZ-LUB', 'Lubombo', 'lubombo', null, null),
  ('SZ', 1, 'SZ-MAN', 'Manzini', 'manzini', null, null),
  ('SZ', 1, 'SZ-SHI', 'Shiselweni', 'shiselweni', null, null),
  ('ET', 1, 'ET-ADD', 'Addis Ababa', 'addis ababa', null, null),
  ('ET', 1, 'ET-AFA', 'Afar', 'afar', null, null),
  ('ET', 1, 'ET-AMH', 'Amhara', 'amhara', null, null),
  ('ET', 1, 'ET-BEN', 'Benishangul-Gumuz', 'benishangul-gumuz', null, null),
  ('ET', 1, 'ET-CEN', 'Central Ethiopia', 'central ethiopia', null, null),
  ('ET', 1, 'ET-DIR', 'Dire Dawa', 'dire dawa', null, null),
  ('ET', 1, 'ET-GAM', 'Gambela', 'gambela', null, null),
  ('ET', 1, 'ET-HAR', 'Harari', 'harari', null, null),
  ('ET', 1, 'ET-ORO', 'Oromia', 'oromia', null, null),
  ('ET', 1, 'ET-SID', 'Sidama', 'sidama', null, null),
  ('ET', 1, 'ET-SOM', 'Somali', 'somali', null, null),
  ('ET', 1, 'ET-SOU', 'South Ethiopia', 'south ethiopia', null, null),
  ('ET', 1, 'ET-SOUT', 'South West Ethiopia', 'south west ethiopia', null, null),
  ('ET', 1, 'ET-TIG', 'Tigray', 'tigray', null, null),
  ('GA', 1, 'GA-EST', 'Estuaire', 'estuaire', null, null),
  ('GA', 1, 'GA-HAU', 'Haut-Ogooué', 'haut-ogooue', null, null),
  ('GA', 1, 'GA-MOY', 'Moyen-Ogooué', 'moyen-ogooue', null, null),
  ('GA', 1, 'GA-NGO', 'Ngounié', 'ngounie', null, null),
  ('GA', 1, 'GA-NYA', 'Nyanga', 'nyanga', null, null),
  ('GA', 1, 'GA-OGO', 'Ogooué-Ivindo', 'ogooue-ivindo', null, null),
  ('GA', 1, 'GA-OGOO', 'Ogooué-Lolo', 'ogooue-lolo', null, null),
  ('GA', 1, 'GA-OGU', 'Ogooué-Maritime', 'ogooue-maritime', null, null),
  ('GA', 1, 'GA-WOL', 'Woleu-Ntem', 'woleu-ntem', null, null),
  ('GM', 1, 'GM-BAN', 'Banjul', 'banjul', null, null),
  ('GM', 1, 'GM-KAN', 'Kanifing', 'kanifing', null, null),
  ('GM', 1, 'GM-BRI', 'Brikama', 'brikama', null, null),
  ('GM', 1, 'GM-MAN', 'Mansakonko', 'mansakonko', null, null),
  ('GM', 1, 'GM-KER', 'Kerewan', 'kerewan', null, null),
  ('GM', 1, 'GM-KUN', 'Kuntaur', 'kuntaur', null, null),
  ('GM', 1, 'GM-JAN', 'Janjanbureh', 'janjanbureh', null, null),
  ('GM', 1, 'GM-BAS', 'Basse', 'basse', null, null),
  ('GH', 1, 'GH-AHA', 'Ahafo', 'ahafo', null, null),
  ('GH', 1, 'GH-ASH', 'Ashanti', 'ashanti', null, null),
  ('GH', 1, 'GH-BON', 'Bono', 'bono', null, null),
  ('GH', 1, 'GH-BONO', 'Bono East', 'bono east', null, null),
  ('GH', 1, 'GH-CEN', 'Central', 'central', null, null),
  ('GH', 1, 'GH-EAS', 'Eastern', 'eastern', null, null),
  ('GH', 1, 'GH-GRE', 'Greater Accra', 'greater accra', null, null),
  ('GH', 1, 'GH-NOR', 'North East', 'north east', null, null),
  ('GH', 1, 'GH-NORT', 'Northern', 'northern', null, null),
  ('GH', 1, 'GH-OTI', 'Oti', 'oti', null, null),
  ('GH', 1, 'GH-SAV', 'Savannah', 'savannah', null, null),
  ('GH', 1, 'GH-UPP', 'Upper East', 'upper east', null, null),
  ('GH', 1, 'GH-UPPE', 'Upper West', 'upper west', null, null),
  ('GH', 1, 'GH-VOL', 'Volta', 'volta', null, null),
  ('GH', 1, 'GH-WES', 'Western', 'western', null, null),
  ('GH', 1, 'GH-WEST', 'Western North', 'western north', null, null),
  ('GN', 1, 'GN-BOK', 'Boké', 'boke', null, null),
  ('GN', 1, 'GN-CON', 'Conakry', 'conakry', null, null),
  ('GN', 1, 'GN-FAR', 'Faranah', 'faranah', null, null),
  ('GN', 1, 'GN-KAN', 'Kankan', 'kankan', null, null),
  ('GN', 1, 'GN-KIN', 'Kindia', 'kindia', null, null),
  ('GN', 1, 'GN-LAB', 'Labé', 'labe', null, null),
  ('GN', 1, 'GN-MAM', 'Mamou', 'mamou', null, null),
  ('GN', 1, 'GN-NZE', 'Nzérékoré', 'nzerekore', null, null),
  ('GW', 1, 'GW-BAF', 'Bafatá', 'bafata', null, null),
  ('GW', 1, 'GW-BIO', 'Biombo', 'biombo', null, null),
  ('GW', 1, 'GW-BIS', 'Bissau', 'bissau', null, null),
  ('GW', 1, 'GW-BOL', 'Bolama', 'bolama', null, null),
  ('GW', 1, 'GW-CAC', 'Cacheu', 'cacheu', null, null),
  ('GW', 1, 'GW-GAB', 'Gabú', 'gabu', null, null),
  ('GW', 1, 'GW-OIO', 'Oio', 'oio', null, null),
  ('GW', 1, 'GW-QUI', 'Quinara', 'quinara', null, null),
  ('GW', 1, 'GW-TOM', 'Tombali', 'tombali', null, null),
  ('KE', 1, 'KE-MOM', 'Mombasa', 'mombasa', null, null),
  ('KE', 1, 'KE-KWA', 'Kwale', 'kwale', null, null),
  ('KE', 1, 'KE-KIL', 'Kilifi', 'kilifi', null, null),
  ('KE', 1, 'KE-TAN', 'Tana River', 'tana river', null, null),
  ('KE', 1, 'KE-LAM', 'Lamu', 'lamu', null, null),
  ('KE', 1, 'KE-TAI', 'Taita-Taveta', 'taita-taveta', null, null),
  ('KE', 1, 'KE-GAR', 'Garissa', 'garissa', null, null),
  ('KE', 1, 'KE-WAJ', 'Wajir', 'wajir', null, null),
  ('KE', 1, 'KE-MAN', 'Mandera', 'mandera', null, null),
  ('KE', 1, 'KE-MAR', 'Marsabit', 'marsabit', null, null),
  ('KE', 1, 'KE-ISI', 'Isiolo', 'isiolo', null, null),
  ('KE', 1, 'KE-MER', 'Meru', 'meru', null, null),
  ('KE', 1, 'KE-THA', 'Tharaka-Nithi', 'tharaka-nithi', null, null),
  ('KE', 1, 'KE-EMB', 'Embu', 'embu', null, null),
  ('KE', 1, 'KE-KIT', 'Kitui', 'kitui', null, null),
  ('KE', 1, 'KE-MAC', 'Machakos', 'machakos', null, null),
  ('KE', 1, 'KE-MAK', 'Makueni', 'makueni', null, null),
  ('KE', 1, 'KE-NYA', 'Nyandarua', 'nyandarua', null, null),
  ('KE', 1, 'KE-NYE', 'Nyeri', 'nyeri', null, null),
  ('KE', 1, 'KE-KIR', 'Kirinyaga', 'kirinyaga', null, null),
  ('KE', 1, 'KE-MUR', 'Murang''a', 'murang''a', null, null),
  ('KE', 1, 'KE-KIA', 'Kiambu', 'kiambu', null, null),
  ('KE', 1, 'KE-TUR', 'Turkana', 'turkana', null, null),
  ('KE', 1, 'KE-WES', 'West Pokot', 'west pokot', null, null),
  ('KE', 1, 'KE-SAM', 'Samburu', 'samburu', null, null),
  ('KE', 1, 'KE-TRA', 'Trans-Nzoia', 'trans-nzoia', null, null),
  ('KE', 1, 'KE-UAS', 'Uasin Gishu', 'uasin gishu', null, null),
  ('KE', 1, 'KE-ELG', 'Elgeyo-Marakwet', 'elgeyo-marakwet', null, null),
  ('KE', 1, 'KE-NAN', 'Nandi', 'nandi', null, null),
  ('KE', 1, 'KE-BAR', 'Baringo', 'baringo', null, null),
  ('KE', 1, 'KE-LAI', 'Laikipia', 'laikipia', null, null),
  ('KE', 1, 'KE-NAK', 'Nakuru', 'nakuru', null, null),
  ('KE', 1, 'KE-NAR', 'Narok', 'narok', null, null),
  ('KE', 1, 'KE-KAJ', 'Kajiado', 'kajiado', null, null),
  ('KE', 1, 'KE-KER', 'Kericho', 'kericho', null, null),
  ('KE', 1, 'KE-BOM', 'Bomet', 'bomet', null, null),
  ('KE', 1, 'KE-KAK', 'Kakamega', 'kakamega', null, null),
  ('KE', 1, 'KE-VIH', 'Vihiga', 'vihiga', null, null),
  ('KE', 1, 'KE-BUN', 'Bungoma', 'bungoma', null, null),
  ('KE', 1, 'KE-BUS', 'Busia', 'busia', null, null),
  ('KE', 1, 'KE-SIA', 'Siaya', 'siaya', null, null),
  ('KE', 1, 'KE-KIS', 'Kisumu', 'kisumu', null, null),
  ('KE', 1, 'KE-HOM', 'Homa Bay', 'homa bay', null, null),
  ('KE', 1, 'KE-MIG', 'Migori', 'migori', null, null),
  ('KE', 1, 'KE-KISI', 'Kisii', 'kisii', null, null),
  ('KE', 1, 'KE-NYAM', 'Nyamira', 'nyamira', null, null),
  ('KE', 1, 'KE-NAI', 'Nairobi', 'nairobi', null, null),
  ('LS', 1, 'LS-BER', 'Berea', 'berea', null, null),
  ('LS', 1, 'LS-BUT', 'Butha-Buthe', 'butha-buthe', null, null),
  ('LS', 1, 'LS-LER', 'Leribe', 'leribe', null, null),
  ('LS', 1, 'LS-MAF', 'Mafeteng', 'mafeteng', null, null),
  ('LS', 1, 'LS-MAS', 'Maseru', 'maseru', null, null),
  ('LS', 1, 'LS-MOH', 'Mohale''s Hoek', 'mohale''s hoek', null, null),
  ('LS', 1, 'LS-MOK', 'Mokhotlong', 'mokhotlong', null, null),
  ('LS', 1, 'LS-QAC', 'Qacha''s Nek', 'qacha''s nek', null, null),
  ('LS', 1, 'LS-QUT', 'Quthing', 'quthing', null, null),
  ('LS', 1, 'LS-THA', 'Thaba-Tseka', 'thaba-tseka', null, null),
  ('LR', 1, 'LR-BOM', 'Bomi', 'bomi', null, null),
  ('LR', 1, 'LR-BON', 'Bong', 'bong', null, null),
  ('LR', 1, 'LR-GBA', 'Gbarpolu', 'gbarpolu', null, null),
  ('LR', 1, 'LR-GRA', 'Grand Bassa', 'grand bassa', null, null),
  ('LR', 1, 'LR-GRAN', 'Grand Cape Mount', 'grand cape mount', null, null),
  ('LR', 1, 'LR-GRN', 'Grand Gedeh', 'grand gedeh', null, null),
  ('LR', 1, 'LR-GRD', 'Grand Kru', 'grand kru', null, null),
  ('LR', 1, 'LR-LOF', 'Lofa', 'lofa', null, null),
  ('LR', 1, 'LR-MAR', 'Margibi', 'margibi', null, null),
  ('LR', 1, 'LR-MARY', 'Maryland', 'maryland', null, null),
  ('LR', 1, 'LR-MON', 'Montserrado', 'montserrado', null, null),
  ('LR', 1, 'LR-NIM', 'Nimba', 'nimba', null, null),
  ('LR', 1, 'LR-RIV', 'River Cess', 'river cess', null, null),
  ('LR', 1, 'LR-RIVE', 'River Gee', 'river gee', null, null),
  ('LR', 1, 'LR-SIN', 'Sinoe', 'sinoe', null, null),
  ('LY', 1, 'LY-TRI', 'Tripoli', 'tripoli', null, null),
  ('LY', 1, 'LY-BEN', 'Benghazi', 'benghazi', null, null),
  ('LY', 1, 'LY-MIS', 'Misrata', 'misrata', null, null),
  ('LY', 1, 'LY-ALM', 'Al Marj', 'al marj', null, null),
  ('LY', 1, 'LY-ALJ', 'Al Jabal al Akhdar', 'al jabal al akhdar', null, null),
  ('LY', 1, 'LY-ALJA', 'Al Jafara', 'al jafara', null, null),
  ('LY', 1, 'LY-ALJU', 'Al Jufra', 'al jufra', null, null),
  ('LY', 1, 'LY-ALK', 'Al Kufrah', 'al kufrah', null, null),
  ('LY', 1, 'LY-ALW', 'Al Wahat', 'al wahat', null, null),
  ('LY', 1, 'LY-ANN', 'An Nuqat al Khams', 'an nuqat al khams', null, null),
  ('LY', 1, 'LY-AZZ', 'Az Zawiyah', 'az zawiyah', null, null),
  ('LY', 1, 'LY-DAR', 'Darnah', 'darnah', null, null),
  ('LY', 1, 'LY-GHA', 'Ghat', 'ghat', null, null),
  ('LY', 1, 'LY-MUR', 'Murzuq', 'murzuq', null, null),
  ('LY', 1, 'LY-NAL', 'Nalut', 'nalut', null, null),
  ('LY', 1, 'LY-SAB', 'Sabha', 'sabha', null, null),
  ('LY', 1, 'LY-SIR', 'Sirte', 'sirte', null, null),
  ('LY', 1, 'LY-WAD', 'Wadi al Hayaa', 'wadi al hayaa', null, null),
  ('LY', 1, 'LY-WADI', 'Wadi al Shatii', 'wadi al shatii', null, null),
  ('LY', 1, 'LY-ALB', 'Al Butnan', 'al butnan', null, null),
  ('LY', 1, 'LY-ALA', 'Al Jabal al Gharbi', 'al jabal al gharbi', null, null),
  ('LY', 1, 'LY-MURQ', 'Murqub', 'murqub', null, null),
  ('MG', 1, 'MG-ALA', 'Alaotra-Mangoro', 'alaotra-mangoro', null, null),
  ('MG', 1, 'MG-AMO', 'Amoron''i Mania', 'amoron''i mania', null, null),
  ('MG', 1, 'MG-ANA', 'Analamanga', 'analamanga', null, null),
  ('MG', 1, 'MG-ANAL', 'Analanjirofo', 'analanjirofo', null, null),
  ('MG', 1, 'MG-AND', 'Androy', 'androy', null, null),
  ('MG', 1, 'MG-ANO', 'Anosy', 'anosy', null, null),
  ('MG', 1, 'MG-ATS', 'Atsimo-Andrefana', 'atsimo-andrefana', null, null),
  ('MG', 1, 'MG-ATSI', 'Atsimo-Atsinanana', 'atsimo-atsinanana', null, null),
  ('MG', 1, 'MG-ATI', 'Atsinanana', 'atsinanana', null, null),
  ('MG', 1, 'MG-BET', 'Betsiboka', 'betsiboka', null, null),
  ('MG', 1, 'MG-BOE', 'Boeny', 'boeny', null, null),
  ('MG', 1, 'MG-BON', 'Bongolava', 'bongolava', null, null),
  ('MG', 1, 'MG-DIA', 'Diana', 'diana', null, null),
  ('MG', 1, 'MG-FIT', 'Fitovinany', 'fitovinany', null, null),
  ('MG', 1, 'MG-HAU', 'Haute Matsiatra', 'haute matsiatra', null, null),
  ('MG', 1, 'MG-IHO', 'Ihorombe', 'ihorombe', null, null),
  ('MG', 1, 'MG-ITA', 'Itasy', 'itasy', null, null),
  ('MG', 1, 'MG-MEL', 'Melaky', 'melaky', null, null),
  ('MG', 1, 'MG-MEN', 'Menabe', 'menabe', null, null),
  ('MG', 1, 'MG-SAV', 'Sava', 'sava', null, null),
  ('MG', 1, 'MG-SOF', 'Sofia', 'sofia', null, null),
  ('MG', 1, 'MG-VAK', 'Vakinankaratra', 'vakinankaratra', null, null),
  ('MG', 1, 'MG-VAT', 'Vatovavy', 'vatovavy', null, null),
  ('MW', 1, 'MW-BAL', 'Balaka', 'balaka', null, null),
  ('MW', 1, 'MW-BLA', 'Blantyre', 'blantyre', null, null),
  ('MW', 1, 'MW-CHI', 'Chikwawa', 'chikwawa', null, null),
  ('MW', 1, 'MW-CHIR', 'Chiradzulu', 'chiradzulu', null, null),
  ('MW', 1, 'MW-CHIT', 'Chitipa', 'chitipa', null, null),
  ('MW', 1, 'MW-DED', 'Dedza', 'dedza', null, null),
  ('MW', 1, 'MW-DOW', 'Dowa', 'dowa', null, null),
  ('MW', 1, 'MW-KAR', 'Karonga', 'karonga', null, null),
  ('MW', 1, 'MW-KAS', 'Kasungu', 'kasungu', null, null),
  ('MW', 1, 'MW-LIK', 'Likoma', 'likoma', null, null),
  ('MW', 1, 'MW-LIL', 'Lilongwe', 'lilongwe', null, null),
  ('MW', 1, 'MW-MAC', 'Machinga', 'machinga', null, null),
  ('MW', 1, 'MW-MAN', 'Mangochi', 'mangochi', null, null),
  ('MW', 1, 'MW-MCH', 'Mchinji', 'mchinji', null, null),
  ('MW', 1, 'MW-MUL', 'Mulanje', 'mulanje', null, null),
  ('MW', 1, 'MW-MWA', 'Mwanza', 'mwanza', null, null),
  ('MW', 1, 'MW-MZI', 'Mzimba', 'mzimba', null, null),
  ('MW', 1, 'MW-NEN', 'Neno', 'neno', null, null),
  ('MW', 1, 'MW-NKH', 'Nkhata Bay', 'nkhata bay', null, null),
  ('MW', 1, 'MW-NKHO', 'Nkhotakota', 'nkhotakota', null, null),
  ('MW', 1, 'MW-NSA', 'Nsanje', 'nsanje', null, null),
  ('MW', 1, 'MW-NTC', 'Ntcheu', 'ntcheu', null, null),
  ('MW', 1, 'MW-NTCH', 'Ntchisi', 'ntchisi', null, null),
  ('MW', 1, 'MW-PHA', 'Phalombe', 'phalombe', null, null),
  ('MW', 1, 'MW-RUM', 'Rumphi', 'rumphi', null, null),
  ('MW', 1, 'MW-SAL', 'Salima', 'salima', null, null),
  ('MW', 1, 'MW-THY', 'Thyolo', 'thyolo', null, null),
  ('MW', 1, 'MW-ZOM', 'Zomba', 'zomba', null, null),
  ('ML', 1, 'ML-KAY', 'Kayes', 'kayes', null, null),
  ('ML', 1, 'ML-KOU', 'Koulikoro', 'koulikoro', null, null),
  ('ML', 1, 'ML-SIK', 'Sikasso', 'sikasso', null, null),
  ('ML', 1, 'ML-SEG', 'Ségou', 'segou', null, null),
  ('ML', 1, 'ML-MOP', 'Mopti', 'mopti', null, null),
  ('ML', 1, 'ML-TOM', 'Tombuctu', 'tombuctu', null, null),
  ('ML', 1, 'ML-GAO', 'Gao', 'gao', null, null),
  ('ML', 1, 'ML-KID', 'Kidal', 'kidal', null, null),
  ('ML', 1, 'ML-TAO', 'Taoudénit', 'taoudenit', null, null),
  ('ML', 1, 'ML-MEN', 'Ménaka', 'menaka', null, null),
  ('ML', 1, 'ML-BAM', 'Bamako', 'bamako', null, null),
  ('MR', 1, 'MR-ADR', 'Adrar', 'adrar', null, null),
  ('MR', 1, 'MR-ASS', 'Assaba', 'assaba', null, null),
  ('MR', 1, 'MR-BRA', 'Brakna', 'brakna', null, null),
  ('MR', 1, 'MR-DAK', 'Dakhlet Nouadhibou', 'dakhlet nouadhibou', null, null),
  ('MR', 1, 'MR-GOR', 'Gorgol', 'gorgol', null, null),
  ('MR', 1, 'MR-GUI', 'Guidimaka', 'guidimaka', null, null),
  ('MR', 1, 'MR-HOD', 'Hodh Ech Chargui', 'hodh ech chargui', null, null),
  ('MR', 1, 'MR-HODH', 'Hodh El Gharbi', 'hodh el gharbi', null, null),
  ('MR', 1, 'MR-INC', 'Inchiri', 'inchiri', null, null),
  ('MR', 1, 'MR-NOU', 'Nouakchott-Nord', 'nouakchott-nord', null, null),
  ('MR', 1, 'MR-NOUA', 'Nouakchott-Ouest', 'nouakchott-ouest', null, null),
  ('MR', 1, 'MR-NOA', 'Nouakchott-Sud', 'nouakchott-sud', null, null),
  ('MR', 1, 'MR-TAG', 'Tagant', 'tagant', null, null),
  ('MR', 1, 'MR-TIR', 'Tiris Zemmour', 'tiris zemmour', null, null),
  ('MR', 1, 'MR-TRA', 'Trarza', 'trarza', null, null),
  ('MU', 1, 'MU-BLA', 'Black River', 'black river', null, null),
  ('MU', 1, 'MU-FLA', 'Flacq', 'flacq', null, null),
  ('MU', 1, 'MU-GRA', 'Grand Port', 'grand port', null, null),
  ('MU', 1, 'MU-MOK', 'Moka', 'moka', null, null),
  ('MU', 1, 'MU-PAM', 'Pamplemousses', 'pamplemousses', null, null),
  ('MU', 1, 'MU-PLA', 'Plaines Wilhems', 'plaines wilhems', null, null),
  ('MU', 1, 'MU-POR', 'Port Louis', 'port louis', null, null),
  ('MU', 1, 'MU-RIV', 'Rivière du Rempart', 'riviere du rempart', null, null),
  ('MU', 1, 'MU-SAV', 'Savanne', 'savanne', null, null),
  ('MU', 1, 'MU-ROD', 'Rodrigues', 'rodrigues', null, null),
  ('MA', 1, 'MA-TAN', 'Tânger-Tetuão-Alhucemas', 'tanger-tetuao-alhucemas', null, null),
  ('MA', 1, 'MA-ORI', 'Oriental', 'oriental', null, null),
  ('MA', 1, 'MA-FEZ', 'Fez-Mequinez', 'fez-mequinez', null, null),
  ('MA', 1, 'MA-RAB', 'Rabat-Salé-Quenitra', 'rabat-sale-quenitra', null, null),
  ('MA', 1, 'MA-BEN', 'Beni Melal-Khenifra', 'beni melal-khenifra', null, null),
  ('MA', 1, 'MA-CAS', 'Casablanca-Settat', 'casablanca-settat', null, null),
  ('MA', 1, 'MA-MAR', 'Marraquexe-Safi', 'marraquexe-safi', null, null),
  ('MA', 1, 'MA-DRA', 'Drâa-Tafilalet', 'draa-tafilalet', null, null),
  ('MA', 1, 'MA-SOU', 'Souss-Massa', 'souss-massa', null, null),
  ('MA', 1, 'MA-GUE', 'Guelmim-Oued Noun', 'guelmim-oued noun', null, null),
  ('MA', 1, 'MA-LAA', 'Laâyoune-Saguia el Hamra', 'laayoune-saguia el hamra', null, null),
  ('MA', 1, 'MA-DAK', 'Dakhla-Oued Ed-Dahab', 'dakhla-oued ed-dahab', null, null),
  ('MZ', 1, 'MZ-CAB', 'Cabo Delgado', 'cabo delgado', null, null),
  ('MZ', 1, 'MZ-GAZ', 'Gaza', 'gaza', null, null),
  ('MZ', 1, 'MZ-INH', 'Inhambane', 'inhambane', null, null),
  ('MZ', 1, 'MZ-MAN', 'Manica', 'manica', null, null),
  ('MZ', 1, 'MZ-MAP', 'Maputo', 'maputo', null, null),
  ('MZ', 1, 'MZ-MAPU', 'Maputo Cidade', 'maputo cidade', null, null),
  ('MZ', 1, 'MZ-NAM', 'Nampula', 'nampula', null, null),
  ('MZ', 1, 'MZ-NIA', 'Niassa', 'niassa', null, null),
  ('MZ', 1, 'MZ-SOF', 'Sofala', 'sofala', null, null),
  ('MZ', 1, 'MZ-TET', 'Tete', 'tete', null, null),
  ('MZ', 1, 'MZ-ZAM', 'Zambézia', 'zambezia', null, null),
  ('NA', 1, 'NA-ERO', 'Erongo', 'erongo', null, null),
  ('NA', 1, 'NA-HAR', 'Hardap', 'hardap', null, null),
  ('NA', 1, 'NA-KAR', 'ǁKaras', 'ǁkaras', null, null),
  ('NA', 1, 'NA-KAV', 'Kavango East', 'kavango east', null, null),
  ('NA', 1, 'NA-KAVA', 'Kavango West', 'kavango west', null, null),
  ('NA', 1, 'NA-KHO', 'Khomas', 'khomas', null, null),
  ('NA', 1, 'NA-KUN', 'Kunene', 'kunene', null, null),
  ('NA', 1, 'NA-OHA', 'Ohangwena', 'ohangwena', null, null),
  ('NA', 1, 'NA-OMA', 'Omaheke', 'omaheke', null, null),
  ('NA', 1, 'NA-OMU', 'Omusati', 'omusati', null, null),
  ('NA', 1, 'NA-OSH', 'Oshana', 'oshana', null, null),
  ('NA', 1, 'NA-OSHI', 'Oshikoto', 'oshikoto', null, null),
  ('NA', 1, 'NA-OTJ', 'Otjozondjupa', 'otjozondjupa', null, null),
  ('NA', 1, 'NA-ZAM', 'Zambezi', 'zambezi', null, null),
  ('NE', 1, 'NE-AGA', 'Agadez', 'agadez', null, null),
  ('NE', 1, 'NE-DIF', 'Diffa', 'diffa', null, null),
  ('NE', 1, 'NE-DOS', 'Dosso', 'dosso', null, null),
  ('NE', 1, 'NE-MAR', 'Maradi', 'maradi', null, null),
  ('NE', 1, 'NE-TAH', 'Tahoua', 'tahoua', null, null),
  ('NE', 1, 'NE-TIL', 'Tillabéri', 'tillaberi', null, null),
  ('NE', 1, 'NE-ZIN', 'Zinder', 'zinder', null, null),
  ('NE', 1, 'NE-NIA', 'Niamey', 'niamey', null, null),
  ('NG', 1, 'NG-ABI', 'Abia', 'abia', null, null),
  ('NG', 1, 'NG-ADA', 'Adamawa', 'adamawa', null, null),
  ('NG', 1, 'NG-AKW', 'Akwa Ibom', 'akwa ibom', null, null),
  ('NG', 1, 'NG-ANA', 'Anambra', 'anambra', null, null),
  ('NG', 1, 'NG-BAU', 'Bauchi', 'bauchi', null, null),
  ('NG', 1, 'NG-BAY', 'Bayelsa', 'bayelsa', null, null),
  ('NG', 1, 'NG-BEN', 'Benue', 'benue', null, null),
  ('NG', 1, 'NG-BOR', 'Borno', 'borno', null, null),
  ('NG', 1, 'NG-CRO', 'Cross River', 'cross river', null, null),
  ('NG', 1, 'NG-DEL', 'Delta', 'delta', null, null),
  ('NG', 1, 'NG-EBO', 'Ebonyi', 'ebonyi', null, null),
  ('NG', 1, 'NG-EDO', 'Edo', 'edo', null, null),
  ('NG', 1, 'NG-EKI', 'Ekiti', 'ekiti', null, null),
  ('NG', 1, 'NG-ENU', 'Enugu', 'enugu', null, null),
  ('NG', 1, 'NG-GOM', 'Gombe', 'gombe', null, null),
  ('NG', 1, 'NG-IMO', 'Imo', 'imo', null, null),
  ('NG', 1, 'NG-JIG', 'Jigawa', 'jigawa', null, null),
  ('NG', 1, 'NG-KAD', 'Kaduna', 'kaduna', null, null),
  ('NG', 1, 'NG-KAN', 'Kano', 'kano', null, null),
  ('NG', 1, 'NG-KAT', 'Katsina', 'katsina', null, null),
  ('NG', 1, 'NG-KEB', 'Kebbi', 'kebbi', null, null),
  ('NG', 1, 'NG-KOG', 'Kogi', 'kogi', null, null),
  ('NG', 1, 'NG-KWA', 'Kwara', 'kwara', null, null),
  ('NG', 1, 'NG-LAG', 'Lagos', 'lagos', null, null),
  ('NG', 1, 'NG-NAS', 'Nasarawa', 'nasarawa', null, null),
  ('NG', 1, 'NG-NIG', 'Niger', 'niger', null, null),
  ('NG', 1, 'NG-OGU', 'Ogun', 'ogun', null, null),
  ('NG', 1, 'NG-OND', 'Ondo', 'ondo', null, null),
  ('NG', 1, 'NG-OSU', 'Osun', 'osun', null, null),
  ('NG', 1, 'NG-OYO', 'Oyo', 'oyo', null, null),
  ('NG', 1, 'NG-PLA', 'Plateau', 'plateau', null, null),
  ('NG', 1, 'NG-RIV', 'Rivers', 'rivers', null, null),
  ('NG', 1, 'NG-SOK', 'Sokoto', 'sokoto', null, null),
  ('NG', 1, 'NG-TAR', 'Taraba', 'taraba', null, null),
  ('NG', 1, 'NG-YOB', 'Yobe', 'yobe', null, null),
  ('NG', 1, 'NG-ZAM', 'Zamfara', 'zamfara', null, null),
  ('NG', 1, 'NG-FED', 'Federal Capital Territory', 'federal capital territory', null, null),
  ('RW', 1, 'RW-KIG', 'Kigali', 'kigali', null, null),
  ('RW', 1, 'RW-EAS', 'Eastern', 'eastern', null, null),
  ('RW', 1, 'RW-NOR', 'Northern', 'northern', null, null),
  ('RW', 1, 'RW-SOU', 'Southern', 'southern', null, null),
  ('RW', 1, 'RW-WES', 'Western', 'western', null, null),
  ('ST', 1, 'ST-AGU', 'Água Grande', 'agua grande', null, null),
  ('ST', 1, 'ST-CAN', 'Cantagalo', 'cantagalo', null, null),
  ('ST', 1, 'ST-CAU', 'Caué', 'caue', null, null),
  ('ST', 1, 'ST-LEM', 'Lembá', 'lemba', null, null),
  ('ST', 1, 'ST-LOB', 'Lobata', 'lobata', null, null),
  ('ST', 1, 'ST-MEZ', 'Mé-Zóchi', 'me-zochi', null, null),
  ('ST', 1, 'ST-PRI', 'Príncipe', 'principe', null, null),
  ('SN', 1, 'SN-DAK', 'Dakar', 'dakar', null, null),
  ('SN', 1, 'SN-DIO', 'Diourbel', 'diourbel', null, null),
  ('SN', 1, 'SN-FAT', 'Fatick', 'fatick', null, null),
  ('SN', 1, 'SN-KAF', 'Kaffrine', 'kaffrine', null, null),
  ('SN', 1, 'SN-KAO', 'Kaolack', 'kaolack', null, null),
  ('SN', 1, 'SN-KED', 'Kédougou', 'kedougou', null, null),
  ('SN', 1, 'SN-KOL', 'Kolda', 'kolda', null, null),
  ('SN', 1, 'SN-LOU', 'Louga', 'louga', null, null),
  ('SN', 1, 'SN-MAT', 'Matam', 'matam', null, null),
  ('SN', 1, 'SN-SAI', 'Saint-Louis', 'saint-louis', null, null),
  ('SN', 1, 'SN-SED', 'Sédhiou', 'sedhiou', null, null),
  ('SN', 1, 'SN-TAM', 'Tambacounda', 'tambacounda', null, null),
  ('SN', 1, 'SN-THI', 'Thiès', 'thies', null, null),
  ('SN', 1, 'SN-ZIG', 'Ziguinchor', 'ziguinchor', null, null),
  ('SC', 1, 'SC-ANS', 'Anse aux Pins', 'anse aux pins', null, null),
  ('SC', 1, 'SC-ANSE', 'Anse Boileau', 'anse boileau', null, null),
  ('SC', 1, 'SC-ANE', 'Anse Étoile', 'anse etoile', null, null),
  ('SC', 1, 'SC-AUC', 'Au Cap', 'au cap', null, null),
  ('SC', 1, 'SC-ANR', 'Anse Royale', 'anse royale', null, null),
  ('SC', 1, 'SC-BAI', 'Baie Lazare', 'baie lazare', null, null),
  ('SC', 1, 'SC-BAIE', 'Baie Sainte Anne', 'baie sainte anne', null, null),
  ('SC', 1, 'SC-BEA', 'Beau Vallon', 'beau vallon', null, null),
  ('SC', 1, 'SC-BEL', 'Bel Air', 'bel air', null, null),
  ('SC', 1, 'SC-BELO', 'Bel Ombre', 'bel ombre', null, null),
  ('SC', 1, 'SC-CAS', 'Cascade', 'cascade', null, null),
  ('SC', 1, 'SC-GLA', 'Glacis', 'glacis', null, null),
  ('SC', 1, 'SC-GRA', 'Grand Anse Mahé', 'grand anse mahe', null, null),
  ('SC', 1, 'SC-GRAN', 'Grand Anse Praslin', 'grand anse praslin', null, null),
  ('SC', 1, 'SC-LAD', 'La Digue', 'la digue', null, null),
  ('SC', 1, 'SC-LAR', 'La Rivière Anglaise', 'la riviere anglaise', null, null),
  ('SC', 1, 'SC-LES', 'Les Mamelles', 'les mamelles', null, null),
  ('SC', 1, 'SC-MON', 'Mont Buxton', 'mont buxton', null, null),
  ('SC', 1, 'SC-MONT', 'Mont Fleuri', 'mont fleuri', null, null),
  ('SC', 1, 'SC-PLA', 'Plaisance', 'plaisance', null, null),
  ('SC', 1, 'SC-POI', 'Pointe Larue', 'pointe larue', null, null),
  ('SC', 1, 'SC-POR', 'Port Glaud', 'port glaud', null, null),
  ('SC', 1, 'SC-ROC', 'Roche Caiman', 'roche caiman', null, null),
  ('SC', 1, 'SC-SAI', 'Saint Louis', 'saint louis', null, null),
  ('SC', 1, 'SC-TAK', 'Takamaka', 'takamaka', null, null),
  ('SC', 1, 'SC-ENG', 'English River', 'english river', null, null),
  ('SC', 1, 'SC-INN', 'Inner Islands', 'inner islands', null, null),
  ('SL', 1, 'SL-EAS', 'Eastern', 'eastern', null, null),
  ('SL', 1, 'SL-NOR', 'Northern', 'northern', null, null),
  ('SL', 1, 'SL-NORT', 'North West', 'north west', null, null),
  ('SL', 1, 'SL-SOU', 'Southern', 'southern', null, null),
  ('SL', 1, 'SL-WES', 'Western Area', 'western area', null, null),
  ('SO', 1, 'SO-AWD', 'Awdal', 'awdal', null, null),
  ('SO', 1, 'SO-BAK', 'Bakool', 'bakool', null, null),
  ('SO', 1, 'SO-BAN', 'Banaadir', 'banaadir', null, null),
  ('SO', 1, 'SO-BAR', 'Bari', 'bari', null, null),
  ('SO', 1, 'SO-BAY', 'Bay', 'bay', null, null),
  ('SO', 1, 'SO-GAL', 'Galguduud', 'galguduud', null, null),
  ('SO', 1, 'SO-GED', 'Gedo', 'gedo', null, null),
  ('SO', 1, 'SO-HII', 'Hiiraan', 'hiiraan', null, null),
  ('SO', 1, 'SO-JUB', 'Jubbada Dhexe', 'jubbada dhexe', null, null),
  ('SO', 1, 'SO-JUBB', 'Jubbada Hoose', 'jubbada hoose', null, null),
  ('SO', 1, 'SO-MUD', 'Mudug', 'mudug', null, null),
  ('SO', 1, 'SO-NUG', 'Nugaal', 'nugaal', null, null),
  ('SO', 1, 'SO-SAN', 'Sanaag', 'sanaag', null, null),
  ('SO', 1, 'SO-SHA', 'Shabeellaha Dhexe', 'shabeellaha dhexe', null, null),
  ('SO', 1, 'SO-SHAB', 'Shabeellaha Hoose', 'shabeellaha hoose', null, null),
  ('SO', 1, 'SO-SOO', 'Sool', 'sool', null, null),
  ('SO', 1, 'SO-TOG', 'Togdheer', 'togdheer', null, null),
  ('SO', 1, 'SO-WOQ', 'Woqooyi Galbeed', 'woqooyi galbeed', null, null),
  ('ZA', 1, 'ZA-EAS', 'Eastern Cape', 'eastern cape', null, null),
  ('ZA', 1, 'ZA-FRE', 'Free State', 'free state', null, null),
  ('ZA', 1, 'ZA-GAU', 'Gauteng', 'gauteng', null, null),
  ('ZA', 1, 'ZA-KWA', 'KwaZulu-Natal', 'kwazulu-natal', null, null),
  ('ZA', 1, 'ZA-LIM', 'Limpopo', 'limpopo', null, null),
  ('ZA', 1, 'ZA-MPU', 'Mpumalanga', 'mpumalanga', null, null),
  ('ZA', 1, 'ZA-NOR', 'North West', 'north west', null, null),
  ('ZA', 1, 'ZA-NORT', 'Northern Cape', 'northern cape', null, null),
  ('ZA', 1, 'ZA-WES', 'Western Cape', 'western cape', null, null),
  ('SS', 1, 'SS-CEN', 'Central Equatoria', 'central equatoria', null, null),
  ('SS', 1, 'SS-EAS', 'Eastern Equatoria', 'eastern equatoria', null, null),
  ('SS', 1, 'SS-JON', 'Jonglei', 'jonglei', null, null),
  ('SS', 1, 'SS-LAK', 'Lakes', 'lakes', null, null),
  ('SS', 1, 'SS-NOR', 'Northern Bahr el Ghazal', 'northern bahr el ghazal', null, null),
  ('SS', 1, 'SS-UNI', 'Unity', 'unity', null, null),
  ('SS', 1, 'SS-UPP', 'Upper Nile', 'upper nile', null, null),
  ('SS', 1, 'SS-WAR', 'Warrap', 'warrap', null, null),
  ('SS', 1, 'SS-WES', 'Western Bahr el Ghazal', 'western bahr el ghazal', null, null),
  ('SS', 1, 'SS-WEST', 'Western Equatoria', 'western equatoria', null, null),
  ('SD', 1, 'SD-ALJ', 'Al Jazirah', 'al jazirah', null, null),
  ('SD', 1, 'SD-BLU', 'Blue Nile', 'blue nile', null, null),
  ('SD', 1, 'SD-CEN', 'Central Darfur', 'central darfur', null, null),
  ('SD', 1, 'SD-EAS', 'East Darfur', 'east darfur', null, null),
  ('SD', 1, 'SD-GED', 'Gedaref', 'gedaref', null, null),
  ('SD', 1, 'SD-KAS', 'Kassala', 'kassala', null, null),
  ('SD', 1, 'SD-KHA', 'Khartoum', 'khartoum', null, null),
  ('SD', 1, 'SD-NOR', 'North Darfur', 'north darfur', null, null),
  ('SD', 1, 'SD-NORT', 'North Kordofan', 'north kordofan', null, null),
  ('SD', 1, 'SD-NOT', 'Northern', 'northern', null, null),
  ('SD', 1, 'SD-RED', 'Red Sea', 'red sea', null, null),
  ('SD', 1, 'SD-RIV', 'River Nile', 'river nile', null, null),
  ('SD', 1, 'SD-SEN', 'Sennar', 'sennar', null, null),
  ('SD', 1, 'SD-SOU', 'South Darfur', 'south darfur', null, null),
  ('SD', 1, 'SD-SOUT', 'South Kordofan', 'south kordofan', null, null),
  ('SD', 1, 'SD-WES', 'West Darfur', 'west darfur', null, null),
  ('SD', 1, 'SD-WEST', 'West Kordofan', 'west kordofan', null, null),
  ('SD', 1, 'SD-WHI', 'White Nile', 'white nile', null, null),
  ('TZ', 1, 'TZ-ARU', 'Arusha', 'arusha', null, null),
  ('TZ', 1, 'TZ-DAR', 'Dar es Salaam', 'dar es salaam', null, null),
  ('TZ', 1, 'TZ-DOD', 'Dodoma', 'dodoma', null, null),
  ('TZ', 1, 'TZ-GEI', 'Geita', 'geita', null, null),
  ('TZ', 1, 'TZ-IRI', 'Iringa', 'iringa', null, null),
  ('TZ', 1, 'TZ-KAG', 'Kagera', 'kagera', null, null),
  ('TZ', 1, 'TZ-KAT', 'Katavi', 'katavi', null, null),
  ('TZ', 1, 'TZ-KIG', 'Kigoma', 'kigoma', null, null),
  ('TZ', 1, 'TZ-KIL', 'Kilimanjaro', 'kilimanjaro', null, null),
  ('TZ', 1, 'TZ-LIN', 'Lindi', 'lindi', null, null),
  ('TZ', 1, 'TZ-MAN', 'Manyara', 'manyara', null, null),
  ('TZ', 1, 'TZ-MAR', 'Mara', 'mara', null, null),
  ('TZ', 1, 'TZ-MBE', 'Mbeya', 'mbeya', null, null),
  ('TZ', 1, 'TZ-MOR', 'Morogoro', 'morogoro', null, null),
  ('TZ', 1, 'TZ-MTW', 'Mtwara', 'mtwara', null, null),
  ('TZ', 1, 'TZ-MWA', 'Mwanza', 'mwanza', null, null),
  ('TZ', 1, 'TZ-NJO', 'Njombe', 'njombe', null, null),
  ('TZ', 1, 'TZ-PWA', 'Pwani', 'pwani', null, null),
  ('TZ', 1, 'TZ-RUK', 'Rukwa', 'rukwa', null, null),
  ('TZ', 1, 'TZ-RUV', 'Ruvuma', 'ruvuma', null, null),
  ('TZ', 1, 'TZ-SHI', 'Shinyanga', 'shinyanga', null, null),
  ('TZ', 1, 'TZ-SIM', 'Simiyu', 'simiyu', null, null),
  ('TZ', 1, 'TZ-SIN', 'Singida', 'singida', null, null),
  ('TZ', 1, 'TZ-SON', 'Songwe', 'songwe', null, null),
  ('TZ', 1, 'TZ-TAB', 'Tabora', 'tabora', null, null),
  ('TZ', 1, 'TZ-TAN', 'Tanga', 'tanga', null, null),
  ('TZ', 1, 'TZ-KAS', 'Kaskazini Pemba', 'kaskazini pemba', null, null),
  ('TZ', 1, 'TZ-KASK', 'Kaskazini Unguja', 'kaskazini unguja', null, null),
  ('TZ', 1, 'TZ-KUS', 'Kusini Pemba', 'kusini pemba', null, null),
  ('TZ', 1, 'TZ-KUSI', 'Kusini Unguja', 'kusini unguja', null, null),
  ('TZ', 1, 'TZ-MJI', 'Mjini Magharibi', 'mjini magharibi', null, null),
  ('TG', 1, 'TG-CEN', 'Centrale', 'centrale', null, null),
  ('TG', 1, 'TG-KAR', 'Kara', 'kara', null, null),
  ('TG', 1, 'TG-MAR', 'Maritime', 'maritime', null, null),
  ('TG', 1, 'TG-PLA', 'Plateaux', 'plateaux', null, null),
  ('TG', 1, 'TG-SAV', 'Savanes', 'savanes', null, null),
  ('TN', 1, 'TN-ARI', 'Ariana', 'ariana', null, null),
  ('TN', 1, 'TN-BEJ', 'Béja', 'beja', null, null),
  ('TN', 1, 'TN-BEN', 'Ben Arous', 'ben arous', null, null),
  ('TN', 1, 'TN-BIZ', 'Bizerte', 'bizerte', null, null),
  ('TN', 1, 'TN-GAB', 'Gabès', 'gabes', null, null),
  ('TN', 1, 'TN-GAF', 'Gafsa', 'gafsa', null, null),
  ('TN', 1, 'TN-JEN', 'Jendouba', 'jendouba', null, null),
  ('TN', 1, 'TN-KAI', 'Kairouan', 'kairouan', null, null),
  ('TN', 1, 'TN-KAS', 'Kasserine', 'kasserine', null, null),
  ('TN', 1, 'TN-KEB', 'Kébili', 'kebili', null, null),
  ('TN', 1, 'TN-KEF', 'Kef', 'kef', null, null),
  ('TN', 1, 'TN-MAH', 'Mahdia', 'mahdia', null, null),
  ('TN', 1, 'TN-MAN', 'Manouba', 'manouba', null, null),
  ('TN', 1, 'TN-MED', 'Médenine', 'medenine', null, null),
  ('TN', 1, 'TN-MON', 'Monastir', 'monastir', null, null),
  ('TN', 1, 'TN-NAB', 'Nabeul', 'nabeul', null, null),
  ('TN', 1, 'TN-SFA', 'Sfax', 'sfax', null, null),
  ('TN', 1, 'TN-SID', 'Sidi Bouzid', 'sidi bouzid', null, null),
  ('TN', 1, 'TN-SIL', 'Siliana', 'siliana', null, null),
  ('TN', 1, 'TN-SOU', 'Sousse', 'sousse', null, null),
  ('TN', 1, 'TN-TAT', 'Tataouine', 'tataouine', null, null),
  ('TN', 1, 'TN-TOZ', 'Tozeur', 'tozeur', null, null),
  ('TN', 1, 'TN-TUN', 'Tunis', 'tunis', null, null),
  ('TN', 1, 'TN-ZAG', 'Zaghouan', 'zaghouan', null, null),
  ('UG', 1, 'UG-CEN', 'Central', 'central', null, null),
  ('UG', 1, 'UG-EAS', 'Eastern', 'eastern', null, null),
  ('UG', 1, 'UG-NOR', 'Northern', 'northern', null, null),
  ('UG', 1, 'UG-WES', 'Western', 'western', null, null),
  ('ZM', 1, 'ZM-CEN', 'Central', 'central', null, null),
  ('ZM', 1, 'ZM-COP', 'Copperbelt', 'copperbelt', null, null),
  ('ZM', 1, 'ZM-EAS', 'Eastern', 'eastern', null, null),
  ('ZM', 1, 'ZM-LUA', 'Luapula', 'luapula', null, null),
  ('ZM', 1, 'ZM-LUS', 'Lusaka', 'lusaka', null, null),
  ('ZM', 1, 'ZM-MUC', 'Muchinga', 'muchinga', null, null),
  ('ZM', 1, 'ZM-NOR', 'Northern', 'northern', null, null),
  ('ZM', 1, 'ZM-NORT', 'North-Western', 'north-western', null, null),
  ('ZM', 1, 'ZM-SOU', 'Southern', 'southern', null, null),
  ('ZM', 1, 'ZM-WES', 'Western', 'western', null, null),
  ('ZW', 1, 'ZW-BUL', 'Bulawayo', 'bulawayo', null, null),
  ('ZW', 1, 'ZW-HAR', 'Harare', 'harare', null, null),
  ('ZW', 1, 'ZW-MAN', 'Manicaland', 'manicaland', null, null),
  ('ZW', 1, 'ZW-MAS', 'Mashonaland Central', 'mashonaland central', null, null),
  ('ZW', 1, 'ZW-MASH', 'Mashonaland East', 'mashonaland east', null, null),
  ('ZW', 1, 'ZW-MAH', 'Mashonaland West', 'mashonaland west', null, null),
  ('ZW', 1, 'ZW-MASV', 'Masvingo', 'masvingo', null, null),
  ('ZW', 1, 'ZW-MAT', 'Matabeleland North', 'matabeleland north', null, null),
  ('ZW', 1, 'ZW-MATA', 'Matabeleland South', 'matabeleland south', null, null),
  ('ZW', 1, 'ZW-MID', 'Midlands', 'midlands', null, null)
on conflict (code) do update set name=excluded.name, name_norm=excluded.name_norm;
