-- Angola: divisões canónicas (21 prov / 326 mun / 378 comunas, reforma 2024)
-- copiadas da BD canónica AFROLOC (ljcxqwjvjgobhisqkujr). Códigos AO-<PROV>/AO-<PROV>-<slug>.
-- Comunas (nível 3) têm parent=província (mapeamento comuna→município ainda pendente na fonte).

insert into public.administrative_divisions (country_code, level, code, name, name_norm, parent_code, parent_level) values
  ('AO', 1, 'AO-BGO', 'Bengo', 'bengo', null, null),
  ('AO', 1, 'AO-BGU', 'Benguela', 'benguela', null, null),
  ('AO', 1, 'AO-BIE', 'Bié', 'bie', null, null),
  ('AO', 1, 'AO-CAB', 'Cabinda', 'cabinda', null, null),
  ('AO', 1, 'AO-CNN', 'Cunene', 'cunene', null, null),
  ('AO', 1, 'AO-CNO', 'Cuanza Norte', 'cuanza norte', null, null),
  ('AO', 1, 'AO-CUB', 'Cubango', 'cubango', null, null),
  ('AO', 1, 'AO-CUD', 'Cuando', 'cuando', null, null),
  ('AO', 1, 'AO-CUS', 'Cuanza Sul', 'cuanza sul', null, null),
  ('AO', 1, 'AO-HUA', 'Huambo', 'huambo', null, null),
  ('AO', 1, 'AO-HUI', 'Huíla', 'huila', null, null),
  ('AO', 1, 'AO-ICO', 'Icolo e Bengo', 'icolo e bengo', null, null),
  ('AO', 1, 'AO-LNO', 'Lunda Norte', 'lunda norte', null, null),
  ('AO', 1, 'AO-LSU', 'Lunda Sul', 'lunda sul', null, null),
  ('AO', 1, 'AO-LUA', 'Luanda', 'luanda', null, null),
  ('AO', 1, 'AO-MAL', 'Malanje', 'malanje', null, null),
  ('AO', 1, 'AO-MOX', 'Moxico', 'moxico', null, null),
  ('AO', 1, 'AO-MXL', 'Moxico Leste', 'moxico leste', null, null),
  ('AO', 1, 'AO-NAM', 'Namibe', 'namibe', null, null),
  ('AO', 1, 'AO-UIG', 'Uíge', 'uige', null, null),
  ('AO', 1, 'AO-ZAI', 'Zaire', 'zaire', null, null),
  ('AO', 2, 'AO-BGO-AMBRIZ', 'Ambriz', 'ambriz', 'AO-BGO', 1),
  ('AO', 2, 'AO-BGO-BARRADODA', 'Barra do Dande', 'barra do dande', 'AO-BGO', 1),
  ('AO', 2, 'AO-BGO-BULAATUMB', 'Bula Atumba', 'bula atumba', 'AO-BGO', 1),
  ('AO', 2, 'AO-BGO-DANDE', 'Dande', 'dande', 'AO-BGO', 1),
  ('AO', 2, 'AO-BGO-MUXALUAND', 'Muxaluando', 'muxaluando', 'AO-BGO', 1),
  ('AO', 2, 'AO-BGO-NAMBUANGO', 'Nambuangongo', 'nambuangongo', 'AO-BGO', 1),
  ('AO', 2, 'AO-BGO-PANGOALUQ', 'Pango Aluquém', 'pango aluquem', 'AO-BGO', 1),
  ('AO', 2, 'AO-BGO-PANGUILA', 'Panguila', 'panguila', 'AO-BGO', 1),
  ('AO', 2, 'AO-BGO-PIRI', 'Piri', 'piri', 'AO-BGO', 1),
  ('AO', 2, 'AO-BGO-QUIBAXE', 'Quibaxe', 'quibaxe', 'AO-BGO', 1),
  ('AO', 2, 'AO-BGO-QUICUNZO', 'Quicunzo', 'quicunzo', 'AO-BGO', 1),
  ('AO', 2, 'AO-BGO-UCUA', 'Úcua', 'ucua', 'AO-BGO', 1),
  ('AO', 2, 'AO-BGU-BABERA', 'Babaera', 'babaera', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-BAIAFARTA', 'Baía Farta', 'baia farta', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-BALOMBO', 'Balombo', 'balombo', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-BENGUELA', 'Benguela', 'benguela', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-BIOPIO', 'Biópio', 'biopio', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-BOCOIO', 'Bocoio', 'bocoio', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-BOLONGUER', 'Bolonguera', 'bolonguera', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-CAIMBAMBO', 'Caimbambo', 'caimbambo', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-CANHAMELA', 'Canhamela', 'canhamela', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-CAPUPA', 'Capupa', 'capupa', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-CATENGUE', 'Catengue', 'catengue', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-CATUMBELA', 'Catumbela', 'catumbela', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-CHICUMA', 'Chicuma', 'chicuma', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-CHILA', 'Chila', 'chila', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-CHINDUMBO', 'Chindumbo', 'chindumbo', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-CHONGOROI', 'Chongoroi', 'chongoroi', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-CUBAL', 'Cubal', 'cubal', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-DOMBEGRAN', 'Dombe Grande', 'dombe grande', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-EGIPTOPRA', 'Egipto-Praia', 'egipto-praia', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-GANDA', 'Ganda', 'ganda', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-LOBITO', 'Lobito', 'lobito', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-NAVEGANTE', 'Navegantes', 'navegantes', 'AO-BGU', 1),
  ('AO', 2, 'AO-BGU-YAMBALA', 'Yambala', 'yambala', 'AO-BGU', 1),
  ('AO', 2, 'AO-BIE-ANDULO', 'Andulo', 'andulo', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-BELOHORIZ', 'Belo Horizonte', 'belo horizonte', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-CALUCINGA', 'Calucinga', 'calucinga', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-CAMACUPA', 'Camacupa', 'camacupa', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-CAMBANDUA', 'Cambândua', 'cambandua', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-CATABOLA', 'Catabola', 'catabola', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-CHICALA', 'Chicala', 'chicala', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-CHINGUAR', 'Chinguar', 'chinguar', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-CHIPETA', 'Chipeta', 'chipeta', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-CHITEMBO', 'Chitembo', 'chitembo', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-CUEMBA', 'Cuemba', 'cuemba', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-CUITO', 'Cuíto', 'cuito', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-CUNHINGA', 'Cunhinga', 'cunhinga', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-LUANDO', 'Luando', 'luando', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-LUBIA', 'Lúbia', 'lubia', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-MUMBUE', 'Mumbué', 'mumbue', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-NHAREA', 'Nharêa', 'nharea', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-RINGOMA', 'Ringoma', 'ringoma', 'AO-BIE', 1),
  ('AO', 2, 'AO-BIE-UMPULO', 'Umpulo', 'umpulo', 'AO-BIE', 1),
  ('AO', 2, 'AO-CAB-BELIZE', 'Belize', 'belize', 'AO-CAB', 1),
  ('AO', 2, 'AO-CAB-BUCOZAU', 'Buco Zau', 'buco zau', 'AO-CAB', 1),
  ('AO', 2, 'AO-CAB-CABINDA', 'Cabinda', 'cabinda', 'AO-CAB', 1),
  ('AO', 2, 'AO-CAB-CACONGO', 'Cacongo', 'cacongo', 'AO-CAB', 1),
  ('AO', 2, 'AO-CAB-LIAMBO', 'Liambo', 'liambo', 'AO-CAB', 1),
  ('AO', 2, 'AO-CAB-MASSABI', 'Massabi', 'massabi', 'AO-CAB', 1),
  ('AO', 2, 'AO-CAB-MICONJE', 'Miconje', 'miconje', 'AO-CAB', 1),
  ('AO', 2, 'AO-CAB-NECUTO', 'Necuto', 'necuto', 'AO-CAB', 1),
  ('AO', 2, 'AO-CAB-NGOIO', 'Ngoio', 'ngoio', 'AO-CAB', 1),
  ('AO', 2, 'AO-CAB-TANDOZINZ', 'Tando Zinze', 'tando zinze', 'AO-CAB', 1),
  ('AO', 2, 'AO-CNN-CAFIMA', 'Cafima', 'cafima', 'AO-CNN', 1),
  ('AO', 2, 'AO-CNN-CAHAMA', 'Cahama', 'cahama', 'AO-CNN', 1),
  ('AO', 2, 'AO-CNN-CHIEDE', 'Chiéde', 'chiede', 'AO-CNN', 1),
  ('AO', 2, 'AO-CNN-CHISSUATA', 'Chissuata', 'chissuata', 'AO-CNN', 1),
  ('AO', 2, 'AO-CNN-CHITADO', 'Chitado', 'chitado', 'AO-CNN', 1),
  ('AO', 2, 'AO-CNN-CUANHAMA', 'Cuanhama', 'cuanhama', 'AO-CNN', 1),
  ('AO', 2, 'AO-CNN-CUROCA', 'Curoca', 'curoca', 'AO-CNN', 1),
  ('AO', 2, 'AO-CNN-CUVELAI', 'Cuvelai', 'cuvelai', 'AO-CNN', 1),
  ('AO', 2, 'AO-CNN-HUMBE', 'Humbe', 'humbe', 'AO-CNN', 1),
  ('AO', 2, 'AO-CNN-MUPA', 'Mupa', 'mupa', 'AO-CNN', 1),
  ('AO', 2, 'AO-CNN-NAMACUNDE', 'Namacunde', 'namacunde', 'AO-CNN', 1),
  ('AO', 2, 'AO-CNN-NAULILA', 'Naulila', 'naulila', 'AO-CNN', 1),
  ('AO', 2, 'AO-CNN-NEHONE', 'Nehone', 'nehone', 'AO-CNN', 1),
  ('AO', 2, 'AO-CNN-OMBADJA', 'Ombadja', 'ombadja', 'AO-CNN', 1),
  ('AO', 2, 'AO-CNO-ALDEIANOV', 'Aldeia Nova', 'aldeia nova', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-AMBACA', 'Ambaca', 'ambaca', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-BANGA', 'Banga', 'banga', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-BOLONGONG', 'Bolongongo', 'bolongongo', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-CACULOCAB', 'Caculo Cabaça', 'caculo cabaca', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-CAMBAMBE', 'Cambambe', 'cambambe', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-CAZENGO', 'Cazengo', 'cazengo', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-CERCA', 'Cêrca', 'cerca', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-GOLUNGOAL', 'Golungo Alto', 'golungo alto', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-LUCALA', 'Lucala', 'lucala', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-LUINGA', 'Luinga', 'luinga', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-MASSANGAN', 'Massangano', 'massangano', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-NGONGUEMB', 'Ngonguembo', 'ngonguembo', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-QUICULUNG', 'Quiculungo', 'quiculungo', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-SAMBACAJU', 'Samba Cajú', 'samba caju', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-TANGO', 'Tango', 'tango', 'AO-CNO', 1),
  ('AO', 2, 'AO-CNO-TERREIRO', 'Terreiro', 'terreiro', 'AO-CNO', 1),
  ('AO', 2, 'AO-CUB-CAIUNDO', 'Caiundo', 'caiundo', 'AO-CUB', 1),
  ('AO', 2, 'AO-CUB-CALAI', 'Calai', 'calai', 'AO-CUB', 1),
  ('AO', 2, 'AO-CUB-CHINGUANJ', 'Chinguanja', 'chinguanja', 'AO-CUB', 1),
  ('AO', 2, 'AO-CUB-CUANGAR', 'Cuangar', 'cuangar', 'AO-CUB', 1),
  ('AO', 2, 'AO-CUB-CUCHI', 'Cuchi', 'cuchi', 'AO-CUB', 1),
  ('AO', 2, 'AO-CUB-CUTATO', 'Cutato', 'cutato', 'AO-CUB', 1),
  ('AO', 2, 'AO-CUB-LONGA', 'Longa', 'longa', 'AO-CUB', 1),
  ('AO', 2, 'AO-CUB-MAVENGUE', 'Mavengue', 'mavengue', 'AO-CUB', 1),
  ('AO', 2, 'AO-CUB-MENONGUE', 'Menongue', 'menongue', 'AO-CUB', 1),
  ('AO', 2, 'AO-CUB-NANCOVA', 'Nancova', 'nancova', 'AO-CUB', 1),
  ('AO', 2, 'AO-CUB-SAVATE', 'Savate', 'savate', 'AO-CUB', 1),
  ('AO', 2, 'AO-CUD-CUITOCUAN', 'Cuito Cuanavale', 'cuito cuanavale', 'AO-CUD', 1),
  ('AO', 2, 'AO-CUD-DIMA', 'Dima', 'dima', 'AO-CUD', 1),
  ('AO', 2, 'AO-CUD-DIRICO', 'Dirico', 'dirico', 'AO-CUD', 1),
  ('AO', 2, 'AO-CUD-LUENGUE', 'Luengue', 'luengue', 'AO-CUD', 1),
  ('AO', 2, 'AO-CUD-LUIANA', 'Luiana', 'luiana', 'AO-CUD', 1),
  ('AO', 2, 'AO-CUD-MAVINGA', 'Mavinga', 'mavinga', 'AO-CUD', 1),
  ('AO', 2, 'AO-CUD-MUCUSSO', 'Mucusso', 'mucusso', 'AO-CUD', 1),
  ('AO', 2, 'AO-CUD-RIVUNGO', 'Rivungo', 'rivungo', 'AO-CUD', 1),
  ('AO', 2, 'AO-CUD-XIPUNDO', 'Xipundo', 'xipundo', 'AO-CUD', 1),
  ('AO', 2, 'AO-CUS-AMBOIVA', 'Amboiva', 'amboiva', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-BOAENTRAD', 'Boa Entrada', 'boa entrada', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-CALULO', 'Calulo', 'calulo', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-CASSONGUE', 'Cassongue', 'cassongue', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-CONDA', 'Conda', 'conda', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-CONDE', 'Condé', 'conde', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-EBO', 'Ebo', 'ebo', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-GABELA', 'Gabela', 'gabela', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-GANGULA', 'Gangula', 'gangula', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-GUNGO', 'Gungo', 'gungo', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-LONHE', 'Lonhe', 'lonhe', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-MUNENGA', 'Munenga', 'munenga', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-MUSSENDE', 'Mussende', 'mussende', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-PAMBANGAL', 'Pambangala', 'pambangala', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-PORTOAMBO', 'Porto Amboim', 'porto amboim', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-QUENHA', 'Quenha', 'quenha', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-QUIBALA', 'Quibala', 'quibala', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-QUILENDA', 'Quilenda', 'quilenda', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-QUIRIMBO', 'Quirimbo', 'quirimbo', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-QUISSONGO', 'Quissongo', 'quissongo', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-SANGA', 'Sanga', 'sanga', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-SELES', 'Seles', 'seles', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-SUMBE', 'Sumbe', 'sumbe', 'AO-CUS', 1),
  ('AO', 2, 'AO-CUS-WAKUKUNGO', 'Waku Kungo', 'waku kungo', 'AO-CUS', 1),
  ('AO', 2, 'AO-HUA-ALTOHAMA', 'Alto-Hama', 'alto-hama', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-BAILUNDO', 'Bailundo', 'bailundo', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-BIMBE', 'Bimbe', 'bimbe', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-CAALA', 'Caála', 'caala', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-CACHIUNGO', 'Cachiungo', 'cachiungo', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-CHICALACH', 'Chicala-Cholohanga', 'chicala-cholohanga', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-CHILATA', 'Chilata', 'chilata', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-CHINJENJE', 'Chinjenje', 'chinjenje', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-CUIMA', 'Cuima', 'cuima', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-ECUNHA', 'Ecunha', 'ecunha', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-GALANGA', 'Galanga', 'galanga', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-HUAMBO', 'Huambo', 'huambo', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-LONDUIMBA', 'Londuimbali', 'londuimbali', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-LONGONJO', 'Longonjo', 'longonjo', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-MUNGO', 'Mungo', 'mungo', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-SAMBO', 'Sambo', 'sambo', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUA-UCUMA', 'Ucuma', 'ucuma', 'AO-HUA', 1),
  ('AO', 2, 'AO-HUI-CACONDA', 'Caconda', 'caconda', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-CACULA', 'Cacula', 'cacula', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-CALUQUEMB', 'Caluquembe', 'caluquembe', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-CAPELONGO', 'Capelongo', 'capelongo', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-CAPUNDACA', 'Capunda Cavilongo', 'capunda cavilongo', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-CHIBIA', 'Chibia', 'chibia', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-CHICOMBA', 'Chicomba', 'chicomba', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-CHICUNGO', 'Chicungo', 'chicungo', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-CHIPINDO', 'Chipindo', 'chipindo', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-CHITUTO', 'Chituto', 'chituto', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-CUVANGO', 'Cuvango', 'cuvango', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-DONGO', 'Dongo', 'dongo', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-GALANGUE', 'Galangue', 'galangue', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-GAMBOS', 'Gambos', 'gambos', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-HOQUE', 'Hoque', 'hoque', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-HUMPATA', 'Humpata', 'humpata', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-JAMBA', 'Jamba Mineira', 'jamba mineira', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-LUBANGO', 'Lubango', 'lubango', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-MATALA', 'Matala', 'matala', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-PALANCA', 'Palanca', 'palanca', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-QUILENGUE', 'Quilengues', 'quilengues', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-QUIPUNGO', 'Quipungo', 'quipungo', 'AO-HUI', 1),
  ('AO', 2, 'AO-HUI-VITIVIVAL', 'Viti-Vivali', 'viti-vivali', 'AO-HUI', 1),
  ('AO', 2, 'AO-ICO-BOMJESUS', 'Bom Jesus', 'bom jesus', 'AO-ICO', 1),
  ('AO', 2, 'AO-ICO-CABIRI', 'Cabiri', 'cabiri', 'AO-ICO', 1),
  ('AO', 2, 'AO-ICO-CABOLEDO', 'Cabo Ledo', 'cabo ledo', 'AO-ICO', 1),
  ('AO', 2, 'AO-ICO-CALUMBO', 'Calumbo', 'calumbo', 'AO-ICO', 1),
  ('AO', 2, 'AO-ICO-CATETE', 'Catete', 'catete', 'AO-ICO', 1),
  ('AO', 2, 'AO-ICO-QUICAMA', 'Quiçama', 'quicama', 'AO-ICO', 1),
  ('AO', 2, 'AO-ICO-SEQUELE', 'Sequele', 'sequele', 'AO-ICO', 1),
  ('AO', 2, 'AO-LNO-CAFUNFO', 'Cafunfo', 'cafunfo', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-CAMAXILO', 'Camaxilo', 'camaxilo', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-CAMBULO', 'Cambulo', 'cambulo', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-CANZAR', 'Canzar', 'canzar', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-CAPENDACA', 'Capenda Camulemba', 'capenda camulemba', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-CASSANJEC', 'Cassanje Calucala', 'cassanje calucala', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-CAUNGULA', 'Caungula', 'caungula', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-CHITATO', 'Chitato', 'chitato', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-CUANGO', 'Cuango', 'cuango', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-CUILO', 'Cuilo', 'cuilo', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-DUNDO', 'Dundo', 'dundo', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-LOVUA', 'Lóvua', 'lovua', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-LUANGUE', 'Luangue', 'luangue', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-LUBALO', 'Lubalo', 'lubalo', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-LUCAPA', 'Lucapa', 'lucapa', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-LUREMO', 'Luremo', 'luremo', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-MUSSUNGUE', 'Mussungue', 'mussungue', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-XACASSAU', 'Xá Cassau', 'xa cassau', 'AO-LNO', 1),
  ('AO', 2, 'AO-LNO-XAMUTEBA', 'Xá Muteba', 'xa muteba', 'AO-LNO', 1),
  ('AO', 2, 'AO-LSU-ALTOCHICA', 'Alto Chicapa', 'alto chicapa', 'AO-LSU', 1),
  ('AO', 2, 'AO-LSU-CACOLO', 'Cacolo', 'cacolo', 'AO-LSU', 1),
  ('AO', 2, 'AO-LSU-CASSAISUL', 'Cassai-Sul', 'cassai-sul', 'AO-LSU', 1),
  ('AO', 2, 'AO-LSU-CASSENGO', 'Cassengo', 'cassengo', 'AO-LSU', 1),
  ('AO', 2, 'AO-LSU-CAZAGE', 'Cazage', 'cazage', 'AO-LSU', 1),
  ('AO', 2, 'AO-LSU-CHILUAGE', 'Chiluage', 'chiluage', 'AO-LSU', 1),
  ('AO', 2, 'AO-LSU-DALA', 'Dala', 'dala', 'AO-LSU', 1),
  ('AO', 2, 'AO-LSU-LUMACASSA', 'Luma Cassai', 'luma cassai', 'AO-LSU', 1),
  ('AO', 2, 'AO-LSU-MUANGUEJI', 'Muangueji', 'muangueji', 'AO-LSU', 1),
  ('AO', 2, 'AO-LSU-MUCONDA', 'Muconda', 'muconda', 'AO-LSU', 1),
  ('AO', 2, 'AO-LSU-MURIEGE', 'Muriege', 'muriege', 'AO-LSU', 1),
  ('AO', 2, 'AO-LSU-SAURIMO', 'Saurimo', 'saurimo', 'AO-LSU', 1),
  ('AO', 2, 'AO-LSU-SOMBO', 'Sombo', 'sombo', 'AO-LSU', 1),
  ('AO', 2, 'AO-LSU-XASSENGUE', 'Xassengue', 'xassengue', 'AO-LSU', 1),
  ('AO', 2, 'AO-LUA-BELAS', 'Belas', 'belas', 'AO-LUA', 1),
  ('AO', 2, 'AO-LUA-CACUACO', 'Cacuaco', 'cacuaco', 'AO-LUA', 1),
  ('AO', 2, 'AO-LUA-CAMAMA', 'Camama', 'camama', 'AO-LUA', 1),
  ('AO', 2, 'AO-LUA-CAZENGA', 'Cazenga', 'cazenga', 'AO-LUA', 1),
  ('AO', 2, 'AO-LUA-HOJIYAHEN', 'Hoji ya Henda', 'hoji ya henda', 'AO-LUA', 1),
  ('AO', 2, 'AO-LUA-INGOMBOTA', 'Ingombota', 'ingombota', 'AO-LUA', 1),
  ('AO', 2, 'AO-LUA-KILAMBA', 'Kilamba', 'kilamba', 'AO-LUA', 1),
  ('AO', 2, 'AO-LUA-KILAMBAKI', 'Kilamba Kiaxi', 'kilamba kiaxi', 'AO-LUA', 1),
  ('AO', 2, 'AO-LUA-MAIANGA', 'Maianga', 'maianga', 'AO-LUA', 1),
  ('AO', 2, 'AO-LUA-MULENVOS', 'Mulenvos', 'mulenvos', 'AO-LUA', 1),
  ('AO', 2, 'AO-LUA-MUSSULO', 'Mussulo', 'mussulo', 'AO-LUA', 1),
  ('AO', 2, 'AO-LUA-RANGEL', 'Rangel', 'rangel', 'AO-LUA', 1),
  ('AO', 2, 'AO-LUA-SAMBA', 'Samba', 'samba', 'AO-LUA', 1),
  ('AO', 2, 'AO-LUA-SAMBIZANG', 'Sambizanga', 'sambizanga', 'AO-LUA', 1),
  ('AO', 2, 'AO-LUA-TALATONA', 'Talatona', 'talatona', 'AO-LUA', 1),
  ('AO', 2, 'AO-LUA-VIANA', 'Viana', 'viana', 'AO-LUA', 1),
  ('AO', 2, 'AO-MAL-CACULAMA', 'Caculama', 'caculama', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-CACUSO', 'Cacuso', 'cacuso', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-CAHOMBO', 'Cahombo', 'cahombo', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-CALANDULA', 'Calandula', 'calandula', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-CAMBOSUIN', 'Cambo Suinginge', 'cambo suinginge', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-CAMBUNDIC', 'Cambundi Catembo', 'cambundi catembo', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-CANGANDAL', 'Cangandala', 'cangandala', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-CAPUNDA', 'Capunda', 'capunda', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-CATECOCAN', 'Cateco Cangola', 'cateco cangola', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-CUALE', 'Cuale', 'cuale', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-KIWABANZO', 'Kiwaba Nzoji', 'kiwaba nzoji', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-KUNDADYAB', 'Kunda dya Baze', 'kunda dya baze', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-LUQUEMBO', 'Luquembo', 'luquembo', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-MALANJE', 'Malanje', 'malanje', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-MARIMBA', 'Marimba', 'marimba', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-MASSANGO', 'Massango', 'massango', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-MBANJIYAN', 'Mbanji ya Ngola', 'mbanji ya ngola', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-MILANDO', 'Milando', 'milando', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-MUQUIXE', 'Muquixe', 'muquixe', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-NGOLALUIJ', 'Ngola Luiji', 'ngola luiji', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-PUNGUANDO', 'Pungu a Ndongo', 'pungu a ndongo', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-QUELA', 'Quela', 'quela', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-QUESSUA', 'Quêssua', 'quessua', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-QUIHUHU', 'Quihuhu', 'quihuhu', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-QUIRIMA', 'Quirima', 'quirima', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-QUITAPA', 'Quitapa', 'quitapa', 'AO-MAL', 1),
  ('AO', 2, 'AO-MAL-XANDEL', 'Xandel', 'xandel', 'AO-MAL', 1),
  ('AO', 2, 'AO-MOX-ALTOCUITO', 'Alto Cuito', 'alto cuito', 'AO-MOX', 1),
  ('AO', 2, 'AO-MOX-CAMANONGU', 'Camanongue', 'camanongue', 'AO-MOX', 1),
  ('AO', 2, 'AO-MOX-CANGAMBA', 'Cangamba', 'cangamba', 'AO-MOX', 1),
  ('AO', 2, 'AO-MOX-CANGUMBE', 'Cangumbe', 'cangumbe', 'AO-MOX', 1),
  ('AO', 2, 'AO-MOX-CHIUME', 'Chiúme', 'chiume', 'AO-MOX', 1),
  ('AO', 2, 'AO-MOX-LEUA', 'Léua', 'leua', 'AO-MOX', 1),
  ('AO', 2, 'AO-MOX-LUCUSSE', 'Lucusse', 'lucusse', 'AO-MOX', 1),
  ('AO', 2, 'AO-MOX-LUENA', 'Luena', 'luena', 'AO-MOX', 1),
  ('AO', 2, 'AO-MOX-LUMBALANG', 'Lumbala Nguimbo', 'lumbala nguimbo', 'AO-MOX', 1),
  ('AO', 2, 'AO-MOX-LUTEMBO', 'Lutembo', 'lutembo', 'AO-MOX', 1),
  ('AO', 2, 'AO-MOX-LUTUAI', 'Lutuai', 'lutuai', 'AO-MOX', 1),
  ('AO', 2, 'AO-MOX-NINDA', 'Ninda', 'ninda', 'AO-MOX', 1),
  ('AO', 2, 'AO-MXL-CAIANDA', 'Caianda', 'caianda', 'AO-MXL', 1),
  ('AO', 2, 'AO-MXL-CAMEIA', 'Cameia', 'cameia', 'AO-MXL', 1),
  ('AO', 2, 'AO-MXL-CAZOMBO', 'Cazombo', 'cazombo', 'AO-MXL', 1),
  ('AO', 2, 'AO-MXL-LAGODILOL', 'Lago Dilolo', 'lago dilolo', 'AO-MXL', 1),
  ('AO', 2, 'AO-MXL-LOVUADOZA', 'Lóvua do Zambeze', 'lovua do zambeze', 'AO-MXL', 1),
  ('AO', 2, 'AO-MXL-LUACANO', 'Luacano', 'luacano', 'AO-MXL', 1),
  ('AO', 2, 'AO-MXL-LUAU', 'Luau', 'luau', 'AO-MXL', 1),
  ('AO', 2, 'AO-MXL-MACONDO', 'Macondo', 'macondo', 'AO-MXL', 1),
  ('AO', 2, 'AO-MXL-NANACANDU', 'Nana Candundo', 'nana candundo', 'AO-MXL', 1),
  ('AO', 2, 'AO-NAM-BIBALA', 'Bibala', 'bibala', 'AO-NAM', 1),
  ('AO', 2, 'AO-NAM-CACIMBAS', 'Cacimbas', 'cacimbas', 'AO-NAM', 1),
  ('AO', 2, 'AO-NAM-CAMUCUIO', 'Camucuio', 'camucuio', 'AO-NAM', 1),
  ('AO', 2, 'AO-NAM-IONA', 'Iona', 'iona', 'AO-NAM', 1),
  ('AO', 2, 'AO-NAM-LUCIRA', 'Lucira', 'lucira', 'AO-NAM', 1),
  ('AO', 2, 'AO-NAM-MOCAMEDES', 'Moçâmedes', 'mocamedes', 'AO-NAM', 1),
  ('AO', 2, 'AO-NAM-SACOMAR', 'Sacomar', 'sacomar', 'AO-NAM', 1),
  ('AO', 2, 'AO-NAM-TOMBUA', 'Tômbwa', 'tombwa', 'AO-NAM', 1),
  ('AO', 2, 'AO-NAM-VIREI', 'Virei', 'virei', 'AO-NAM', 1),
  ('AO', 2, 'AO-UIG-ALTOZAZA', 'Alto Zaza', 'alto zaza', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-AMBUILA', 'Ambuíla', 'ambuila', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-BEMBE', 'Bembe', 'bembe', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-BUNGO', 'Bungo', 'bungo', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-CANGOLA', 'Cangola', 'cangola', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-DAMBA', 'Damba', 'damba', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-DANGEQUIT', 'Dange Quitexe', 'dange quitexe', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-LUCUNGA', 'Lucunga', 'lucunga', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-MAQUELADO', 'Maquela do Zombo', 'maquela do zombo', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-MASSAU', 'Massau', 'massau', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-MILUNGA', 'Milunga', 'milunga', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-MUCABA', 'Mucaba', 'mucaba', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-NEGAGE', 'Negage', 'negage', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-NOVAESPER', 'Nova Esperança', 'nova esperanca', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-NSOSSO', 'Nsosso', 'nsosso', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-PURI', 'Puri', 'puri', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-QUIMBELE', 'Quimbele', 'quimbele', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-QUIPEDRO', 'Quipedro', 'quipedro', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-SACANDICA', 'Sacandica', 'sacandica', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-SANZAPOMB', 'Sanza Pombo', 'sanza pombo', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-SONGO', 'Songo', 'songo', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-UIGE', 'Uíge', 'uige', 'AO-UIG', 1),
  ('AO', 2, 'AO-UIG-VISTAALEG', 'Vista Alegre', 'vista alegre', 'AO-UIG', 1),
  ('AO', 2, 'AO-ZAI-CUIMBA', 'Cuimba', 'cuimba', 'AO-ZAI', 1),
  ('AO', 2, 'AO-ZAI-LUFICO', 'Lufico', 'lufico', 'AO-ZAI', 1),
  ('AO', 2, 'AO-ZAI-LUVO', 'Luvo', 'luvo', 'AO-ZAI', 1),
  ('AO', 2, 'AO-ZAI-MBANZAKON', 'Mbanza Kongo', 'mbanza kongo', 'AO-ZAI', 1),
  ('AO', 2, 'AO-ZAI-NOQUI', 'Nóqui', 'noqui', 'AO-ZAI', 1),
  ('AO', 2, 'AO-ZAI-NZETO', 'Nzeto', 'nzeto', 'AO-ZAI', 1),
  ('AO', 2, 'AO-ZAI-QUELO', 'Quêlo', 'quelo', 'AO-ZAI', 1),
  ('AO', 2, 'AO-ZAI-QUINDEJE', 'Quindeje', 'quindeje', 'AO-ZAI', 1),
  ('AO', 2, 'AO-ZAI-SERRADECA', 'Serra de Canda', 'serra de canda', 'AO-ZAI', 1),
  ('AO', 2, 'AO-ZAI-SOYO', 'Soyo', 'soyo', 'AO-ZAI', 1),
  ('AO', 2, 'AO-ZAI-TOMBOCO', 'Tomboco', 'tomboco', 'AO-ZAI', 1),
  ('AO', 3, 'AO-BGO-KAMBRIZ', 'Ambriz', 'ambriz', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KBELAVISTA', 'Bela Vista', 'bela vista', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KBULAATUMB', 'Bula Atumba', 'bula atumba', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KCAGEMAZUM', 'Cage Mazumbo', 'cage mazumbo', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KCANACASSA', 'Canacassala', 'canacassala', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KCAXITO', 'Caxito', 'caxito', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KCAZUANGON', 'Cazuangongo', 'cazuangongo', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KCOXE', 'Coxe', 'coxe', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KGOMBE', 'Gombe', 'gombe', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KMABUBAS', 'Mabubas', 'mabubas', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KMUXALUAND', 'Muxaluando', 'muxaluando', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KPANGOALUQ', 'Pango Aluquém', 'pango aluquem', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KPAREDES', 'Paredes', 'paredes', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KQUIAGE', 'Quiage', 'quiage', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KQUIBAXE', 'Quibaxe', 'quibaxe', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KQUICABO', 'Quicabo', 'quicabo', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KQUIXICO', 'Quixico', 'quixico', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KTABI', 'Tabi', 'tabi', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGO-KZALA', 'Zala', 'zala', 'AO-BGO', 1),
  ('AO', 3, 'AO-BGU-KBALOMBO', 'Balombo', 'balombo', 'AO-BGU', 1),
  ('AO', 3, 'AO-BGU-KBOCOIO', 'Bocoio', 'bocoio', 'AO-BGU', 1),
  ('AO', 3, 'AO-BGU-KCAIAVE', 'Caiave', 'caiave', 'AO-BGU', 1),
  ('AO', 3, 'AO-BGU-KCAIMBAMBO', 'Caimbambo', 'caimbambo', 'AO-BGU', 1),
  ('AO', 3, 'AO-BGU-KCAMUINE', 'Camuine', 'camuine', 'AO-BGU', 1),
  ('AO', 3, 'AO-BGU-KCANJALA', 'Canjala', 'canjala', 'AO-BGU', 1),
  ('AO', 3, 'AO-BGU-KCHONGOROI', 'Chongorói', 'chongoroi', 'AO-BGU', 1),
  ('AO', 3, 'AO-BGU-KCUBALDOLU', 'Cubal do Lumbo', 'cubal do lumbo', 'AO-BGU', 1),
  ('AO', 3, 'AO-BGU-KEGITOPRAI', 'Egito Praia', 'egito praia', 'AO-BGU', 1),
  ('AO', 3, 'AO-BGU-KMACAMOMBO', 'Maca Mombolo', 'maca mombolo', 'AO-BGU', 1),
  ('AO', 3, 'AO-BGU-KMONTEBELO', 'Monte Belo', 'monte belo', 'AO-BGU', 1),
  ('AO', 3, 'AO-BGU-KVIANGOMBE', 'Viangombe', 'viangombe', 'AO-BGU', 1),
  ('AO', 3, 'AO-BIE-KANDULO', 'Andulo', 'andulo', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCACHINGUE', 'Cachingues', 'cachingues', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCAIEIE', 'Caieie', 'caieie', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCAIUERA', 'Caiuera', 'caiuera', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCAMACUPA', 'Camacupa', 'camacupa', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCANGOTE', 'Cangote', 'cangote', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCASSUMBE', 'Cassumbe', 'cassumbe', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCATABOLA', 'Catabola', 'catabola', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCHINGUAR', 'Chinguar', 'chinguar', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCHIPETA', 'Chipeta', 'chipeta', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCHITEMBO', 'Chitembo', 'chitembo', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCHIUCA', 'Chiuca', 'chiuca', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCHIVAULO', 'Chivaúlo', 'chivaulo', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCUANZA', 'Cuanza', 'cuanza', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCUEMBA', 'Cuemba', 'cuemba', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCUITO', 'Cuito', 'cuito', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCUNJE', 'Cunje', 'cunje', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KCUTATO', 'Cutato', 'cutato', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KDANDO', 'Dando', 'dando', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KGAMBA', 'Gamba', 'gamba', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KLUBIA', 'Lúbia', 'lubia', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KMALENGUE', 'Malengue', 'malengue', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KMUINHA', 'Muinha', 'muinha', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KMUMBUE', 'Mumbué', 'mumbue', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KMUNHANGO', 'Munhango', 'munhango', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KMUTUMBO', 'Mutumbo', 'mutumbo', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KNHAREA', 'Nharêa', 'nharea', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KSACHINEMU', 'Sachinemuna', 'sachinemuna', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KSANDE', 'Sande', 'sande', 'AO-BIE', 1),
  ('AO', 3, 'AO-BIE-KSOMACUANZ', 'Soma Cuanza', 'soma cuanza', 'AO-BIE', 1),
  ('AO', 3, 'AO-CAB-KBELIZE', 'Belize', 'belize', 'AO-CAB', 1),
  ('AO', 3, 'AO-CAB-KDINGE', 'Dinge', 'dinge', 'AO-CAB', 1),
  ('AO', 3, 'AO-CAB-KINHUCA', 'Inhuca', 'inhuca', 'AO-CAB', 1),
  ('AO', 3, 'AO-CAB-KLANDANA', 'Lândana', 'landana', 'AO-CAB', 1),
  ('AO', 3, 'AO-CAB-KLUALI', 'Luali', 'luali', 'AO-CAB', 1),
  ('AO', 3, 'AO-CAB-KMALEMBO', 'Malembo', 'malembo', 'AO-CAB', 1),
  ('AO', 3, 'AO-CAB-KNECUTO', 'Necuto', 'necuto', 'AO-CAB', 1),
  ('AO', 3, 'AO-CAB-KTANDOZINZ', 'Tando Zinze', 'tando zinze', 'AO-CAB', 1),
  ('AO', 3, 'AO-CNN-KCAHAMA', 'Cahama', 'cahama', 'AO-CNN', 1),
  ('AO', 3, 'AO-CNN-KEVALE', 'Evale', 'evale', 'AO-CNN', 1),
  ('AO', 3, 'AO-CNN-KHUMBE', 'Humbe', 'humbe', 'AO-CNN', 1),
  ('AO', 3, 'AO-CNN-KMONGUA', 'Môngua', 'mongua', 'AO-CNN', 1),
  ('AO', 3, 'AO-CNN-KMUCOPE', 'Mucope', 'mucope', 'AO-CNN', 1),
  ('AO', 3, 'AO-CNN-KNEHONE', 'Nehone', 'nehone', 'AO-CNN', 1),
  ('AO', 3, 'AO-CNN-KOMBALAYOM', 'Ombala yo Mungu', 'ombala yo mungu', 'AO-CNN', 1),
  ('AO', 3, 'AO-CNN-KONDJIVA', 'Ondjiva', 'ondjiva', 'AO-CNN', 1),
  ('AO', 3, 'AO-CNN-KOTCHINJAU', 'Otchinjau', 'otchinjau', 'AO-CNN', 1),
  ('AO', 3, 'AO-CNN-KXANGONGO', 'Xangongo', 'xangongo', 'AO-CNN', 1),
  ('AO', 3, 'AO-CNO-KBANGA', 'Banga', 'banga', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KBINDO', 'Bindo', 'bindo', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KCACULOCAM', 'Caculo Camuiza', 'caculo camuiza', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KCAMABATEL', 'Camabatela', 'camabatela', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KCAMAME', 'Camame', 'camame', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KCAMBONDO', 'Cambondo', 'cambondo', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KCARIAMBA', 'Cariamba', 'cariamba', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KCAVUNGA', 'Cavunga', 'cavunga', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KDANGEYAME', 'Dange ya Menha', 'dange ya menha', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KDONDO', 'Dondo', 'dondo', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KGOLUNGOAL', 'Golungo Alto', 'golungo alto', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KLUCALA', 'Lucala', 'lucala', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KMASSANGAN', 'Massangano', 'massangano', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KMAUA', 'Máua', 'maua', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KNDALATAND', 'Ndalatando', 'ndalatando', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KQUIANGOMB', 'Quiangombe', 'quiangombe', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KQUILOMBOD', 'Quilombo dos Dembos', 'quilombo dos dembos', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KQUILOMBOQ', 'Quilombo quía Puto', 'quilombo quia puto', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KQUIQUIEMB', 'Quiquiemba', 'quiquiemba', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KSAMBACAJU', 'Samba Cajú', 'samba caju', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KSAMBALUCA', 'Samba Lucala', 'samba lucala', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KSAOPEDROD', 'São Pedro da Quilemba', 'sao pedro da quilemba', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KTERREIRO', 'Terreiro', 'terreiro', 'AO-CNO', 1),
  ('AO', 3, 'AO-CNO-KZENZADOIT', 'Zenza do Itombe', 'zenza do itombe', 'AO-CNO', 1),
  ('AO', 3, 'AO-CUB-KBAIXOLONG', 'Baixo Longa', 'baixo longa', 'AO-CUB', 1),
  ('AO', 3, 'AO-CUB-KBONDOCAIL', 'Bondo Caíla', 'bondo caila', 'AO-CUB', 1),
  ('AO', 3, 'AO-CUB-KCAIUNDO', 'Caiundo', 'caiundo', 'AO-CUB', 1),
  ('AO', 3, 'AO-CUB-KCUTATO', 'Cutato', 'cutato', 'AO-CUB', 1),
  ('AO', 3, 'AO-CUB-KJAMBACUEI', 'Jamba Cueio', 'jamba cueio', 'AO-CUB', 1),
  ('AO', 3, 'AO-CUB-KLONGA', 'Longa', 'longa', 'AO-CUB', 1),
  ('AO', 3, 'AO-CUB-KMAUE', 'Maué', 'maue', 'AO-CUB', 1),
  ('AO', 3, 'AO-CUB-KMAVENGUE', 'Mavengue', 'mavengue', 'AO-CUB', 1),
  ('AO', 3, 'AO-CUB-KNANCOVA', 'Nancova', 'nancova', 'AO-CUB', 1),
  ('AO', 3, 'AO-CUB-KRITO', 'Rito', 'rito', 'AO-CUB', 1),
  ('AO', 3, 'AO-CUB-KSAVATE', 'Savate', 'savate', 'AO-CUB', 1),
  ('AO', 3, 'AO-CUB-KVISSATI', 'Vissati', 'vissati', 'AO-CUB', 1),
  ('AO', 3, 'AO-CUD-KCUITOCUAN', 'Cuito Cuanavale', 'cuito cuanavale', 'AO-CUD', 1),
  ('AO', 3, 'AO-CUD-KCUNJAMBA', 'Cunjamba', 'cunjamba', 'AO-CUD', 1),
  ('AO', 3, 'AO-CUD-KCUTUILE', 'Cutuile', 'cutuile', 'AO-CUD', 1),
  ('AO', 3, 'AO-CUD-KDIRICO', 'Dirico', 'dirico', 'AO-CUD', 1),
  ('AO', 3, 'AO-CUD-KLUPIRE', 'Lupire', 'lupire', 'AO-CUD', 1),
  ('AO', 3, 'AO-CUD-KXAMAVERA', 'Xamavera', 'xamavera', 'AO-CUD', 1),
  ('AO', 3, 'AO-CUS-KASSANGO', 'Assango', 'assango', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KATOME', 'Atóme', 'atome', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KBOTERA', 'Botera', 'botera', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KCABUTA', 'Cabuta', 'cabuta', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KCALULO', 'Calulo', 'calulo', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KCAPOLO', 'Capolo', 'capolo', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KCARIANGO', 'Cariango', 'cariango', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KCASSANJE', 'Cassanje', 'cassanje', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KCASSONGUE', 'Cassongue', 'cassongue', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KCONDA', 'Conda', 'conda', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KCUNJO', 'Cunjo', 'cunjo', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KDALACACHI', 'Dala Cachibo', 'dala cachibo', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KDUMBI', 'Dumbi', 'dumbi', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KEBO', 'Ebo', 'ebo', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KGABELA', 'Gabela', 'gabela', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KLONHE', 'Lonhe', 'lonhe', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KMUSSENDE', 'Mussende', 'mussende', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KPORTOAMBO', 'Porto Amboím', 'porto amboim', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KQUIBALA', 'Quibala', 'quibala', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KQUICOMBO', 'Quicombo', 'quicombo', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KQUIPAXI', 'Quipaxi', 'quipaxi', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KSELES', 'Seles', 'seles', 'AO-CUS', 1),
  ('AO', 3, 'AO-CUS-KSUMBE', 'Sumbe', 'sumbe', 'AO-CUS', 1),
  ('AO', 3, 'AO-HUA-KBAILUNDO', 'Bailundo', 'bailundo', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KBIMBE', 'Bimbe', 'bimbe', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KCACHIUNGO', 'Cachiungo', 'cachiungo', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KCACOMA', 'Cacoma', 'cacoma', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KCALIMA', 'Calima', 'calima', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KCAMBUENGO', 'Cambuengo', 'cambuengo', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KCATATA', 'Catata', 'catata', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KCHIACA', 'Chiaca', 'chiaca', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KCHICALA', 'Chicala', 'chicala', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KCHINHAMA', 'Chinhama', 'chinhama', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KCHINJENJE', 'Chinjenje', 'chinjenje', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KCUIMA', 'Cuima', 'cuima', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KCUMBIRA', 'Cumbira', 'cumbira', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KECUNHA', 'Ecunha', 'ecunha', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KGALANGA', 'Galanga', 'galanga', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KHENGUE', 'Hengue', 'hengue', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KHUAMBO', 'Huambo', 'huambo', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KLEPI', 'Lépi', 'lepi', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KLONDUIMBA', 'Londuimbali', 'londuimbali', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KLONGONJO', 'Longonjo', 'longonjo', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KLUNGE', 'Lunge', 'lunge', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KLUVEMBA', 'Luvemba', 'luvemba', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KMBAVE', 'Mbave', 'mbave', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KMUNDUNDO', 'Mundundo', 'mundundo', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KMUNGO', 'Mungo', 'mungo', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KQUIPEIO', 'Quipeio', 'quipeio', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KSAMBO', 'Sambo', 'sambo', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KSAMBOTO', 'Samboto', 'samboto', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KUCUMA', 'Ucuma', 'ucuma', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUA-KUSSOQUE', 'Ussoque', 'ussoque', 'AO-HUA', 1),
  ('AO', 3, 'AO-HUI-KBAMBI', 'Bambi', 'bambi', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KCACONDA', 'Caconda', 'caconda', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KCACULA', 'Cacula', 'cacula', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KCALEPI', 'Calepi', 'calepi', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KCALUQUEMB', 'Caluquembe', 'caluquembe', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KCAPELONGO', 'Capelongo', 'capelongo', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KCAPUNDACA', 'Capunda Cavilongo', 'capunda cavilongo', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KCASSINGA', 'Cassinga', 'cassinga', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KCHIANGE', 'Chiange', 'chiange', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KCHIBIA', 'Chibia', 'chibia', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KCHICOMBA', 'Chicomba', 'chicomba', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KCHIMBEMBA', 'Chimbemba', 'chimbemba', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KCHIPINDO', 'Chipindo', 'chipindo', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KCUSSE', 'Cusse', 'cusse', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KCUTENDA', 'Cutenda', 'cutenda', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KDINDE', 'Dinde', 'dinde', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KGUNGUE', 'Gungue', 'gungue', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KHUILA', 'Huíla', 'huila', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KIMPULO', 'Impulo', 'impulo', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KJAMBAMINE', 'Jamba Mineira', 'jamba mineira', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KJAU', 'Jau', 'jau', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KLUBANGO', 'Lubango', 'lubango', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KMULONDO', 'Mulondo', 'mulondo', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KNEGOLA', 'Negola', 'negola', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KQUIHITA', 'Quihita', 'quihita', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KQUILENGUE', 'Quilengues', 'quilengues', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KTCHICUAQU', 'Tchicuaqueia', 'tchicuaqueia', 'AO-HUI', 1),
  ('AO', 3, 'AO-HUI-KUABA', 'Uaba', 'uaba', 'AO-HUI', 1),
  ('AO', 3, 'AO-ICO-KCACULOCAH', 'Caculo Cahango', 'caculo cahango', 'AO-ICO', 1),
  ('AO', 3, 'AO-ICO-KCASSONECA', 'Cassoneca', 'cassoneca', 'AO-ICO', 1),
  ('AO', 3, 'AO-ICO-KCATETE', 'Catete', 'catete', 'AO-ICO', 1),
  ('AO', 3, 'AO-ICO-KCAXICANE', 'Caxicane', 'caxicane', 'AO-ICO', 1),
  ('AO', 3, 'AO-ICO-KDEMBACHIO', 'Demba Chio', 'demba chio', 'AO-ICO', 1),
  ('AO', 3, 'AO-ICO-KFUNDA', 'Funda', 'funda', 'AO-ICO', 1),
  ('AO', 3, 'AO-ICO-KMUMBONDO', 'Mumbondo', 'mumbondo', 'AO-ICO', 1),
  ('AO', 3, 'AO-ICO-KMUXIMA', 'Muxima', 'muxima', 'AO-ICO', 1),
  ('AO', 3, 'AO-ICO-KQUIFANGON', 'Quifangondo', 'quifangondo', 'AO-ICO', 1),
  ('AO', 3, 'AO-ICO-KQUIXINGE', 'Quixinge', 'quixinge', 'AO-ICO', 1),
  ('AO', 3, 'AO-ICO-KSEQUELE', 'Sequele', 'sequele', 'AO-ICO', 1),
  ('AO', 3, 'AO-LNO-KCACHIMO', 'Cachimo', 'cachimo', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KCAITA', 'Caíta', 'caita', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KCALUANGO', 'Caluango', 'caluango', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KCAMISSOMB', 'Camissombo', 'camissombo', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KCANZAR', 'Canzar', 'canzar', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KCAPAIA', 'Capaia', 'capaia', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KCAPENDACA', 'Capenda Camulemba', 'capenda camulemba', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KCASSANJEC', 'Cassanje Calucala', 'cassanje calucala', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KCUILO', 'Cuilo', 'cuilo', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KDUNDO', 'Dundo', 'dundo', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KIONGO', 'Iongo', 'iongo', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KLUACHIMO', 'Luachimo', 'luachimo', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KLUBALO', 'Lubalo', 'lubalo', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KLUCAPA', 'Lucapa', 'lucapa', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KLUIA', 'Luia', 'luia', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KMUSSUNGUE', 'Mussungue', 'mussungue', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KMUVULUEGE', 'Muvuluege', 'muvuluege', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KNZAGE', 'Nzage', 'nzage', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KXACASSAU', 'Xá Cassau', 'xa cassau', 'AO-LNO', 1),
  ('AO', 3, 'AO-LNO-KXINGE', 'Xinge', 'xinge', 'AO-LNO', 1),
  ('AO', 3, 'AO-LSU-KCUCUMBI', 'Cucumbi', 'cucumbi', 'AO-LSU', 1),
  ('AO', 3, 'AO-LSU-KMONAQUIMB', 'Mona Quimbundo', 'mona quimbundo', 'AO-LSU', 1),
  ('AO', 3, 'AO-LSU-KSAURIMO', 'Saurimo', 'saurimo', 'AO-LSU', 1),
  ('AO', 3, 'AO-LSU-KXASSENGUE', 'Xassengue', 'xassengue', 'AO-LSU', 1),
  ('AO', 3, 'AO-LUA-KBARRADOCU', 'Barra do Cuanza', 'barra do cuanza', 'AO-LUA', 1),
  ('AO', 3, 'AO-LUA-KBENFICA', 'Benfica', 'benfica', 'AO-LUA', 1),
  ('AO', 3, 'AO-LUA-KCABOLOMBO', 'Cabolombo', 'cabolombo', 'AO-LUA', 1),
  ('AO', 3, 'AO-LUA-KCACUACO', 'Cacuaco', 'cacuaco', 'AO-LUA', 1),
  ('AO', 3, 'AO-LUA-KCAZENGA', 'Cazenga', 'cazenga', 'AO-LUA', 1),
  ('AO', 3, 'AO-LUA-KGOLFE', 'Golfe', 'golfe', 'AO-LUA', 1),
  ('AO', 3, 'AO-LUA-KKIKOLO', 'Kikolo', 'kikolo', 'AO-LUA', 1),
  ('AO', 3, 'AO-LUA-KKILAMBA', 'Kilamba', 'kilamba', 'AO-LUA', 1),
  ('AO', 3, 'AO-LUA-KKIMAKIEZA', 'Kima Kieza', 'kima kieza', 'AO-LUA', 1),
  ('AO', 3, 'AO-LUA-KNOVAVIDA', 'Nova Vida', 'nova vida', 'AO-LUA', 1),
  ('AO', 3, 'AO-LUA-KRAMIROS', 'Ramiros', 'ramiros', 'AO-LUA', 1),
  ('AO', 3, 'AO-LUA-KTALATONA', 'Talatona', 'talatona', 'AO-LUA', 1),
  ('AO', 3, 'AO-LUA-KVILAFLOR', 'Vila Flôr', 'vila flor', 'AO-LUA', 1),
  ('AO', 3, 'AO-MAL-KBANGALAS', 'Bângalas', 'bangalas', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KCABOMBO', 'Cabombo', 'cabombo', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KCACULAMA', 'Caculama', 'caculama', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KCACUSO', 'Cacuso', 'cacuso', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KCAHOMBO', 'Cahombo', 'cahombo', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KCALANDULA', 'Calandula', 'calandula', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KCAMBAXE', 'Cambaxe', 'cambaxe', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KCAMBUNDIC', 'Cambundi Catembo', 'cambundi catembo', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KCANGANDAL', 'Cangandala', 'cangandala', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KCAPUNDA', 'Capunda', 'capunda', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KCARIBO', 'Caribo', 'caribo', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KCAXINGA', 'Caxinga', 'caxinga', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KCOTA', 'Cota', 'cota', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KCULAMAGIA', 'Culamagia', 'culamagia', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KCUNGAPALA', 'Cunga Palanga', 'cunga palanga', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KDOMBOWAZA', 'Dombo wa Zanga', 'dombo wa zanga', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KDUMBACAMB', 'Dumba Cambango', 'dumba cambango', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KKIWABANZO', 'Kiwaba Nzoji', 'kiwaba nzoji', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KKUNDADYAB', 'Kunda dya Baze', 'kunda dya baze', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KLEMBA', 'Lemba', 'lemba', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KLOMBE', 'Lombe', 'lombe', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KLUQUEMBO', 'Luquembo', 'luquembo', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KMALANJE', 'Malanje', 'malanje', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KMANGANDO', 'Mangando', 'mangando', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KMARIMBA', 'Marimba', 'marimba', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KMBANJIYAN', 'Mbanji ya Ngola', 'mbanji ya ngola', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KMICANDA', 'Micanda', 'micanda', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KMOMA', 'Moma', 'moma', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KMUFUMA', 'Mufuma', 'mufuma', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KNGOLALUIJ', 'Ngola Luiji', 'ngola luiji', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KQUELA', 'Quela', 'quela', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KQUIHUHU', 'Quihuhu', 'quihuhu', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KQUIMBANGO', 'Quimbango', 'quimbango', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KQUINGUENG', 'Quinguengue', 'quinguengue', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KQUIRIMA', 'Quirima', 'quirima', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KSAUTAR', 'Sautar', 'sautar', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KSOQUECO', 'Soqueco', 'soqueco', 'AO-MAL', 1),
  ('AO', 3, 'AO-MAL-KXANDEL', 'Xandel', 'xandel', 'AO-MAL', 1),
  ('AO', 3, 'AO-MOX-KCANGAMBA', 'Cangamba', 'cangamba', 'AO-MOX', 1),
  ('AO', 3, 'AO-MOX-KCANGOMBE', 'Cangombe', 'cangombe', 'AO-MOX', 1),
  ('AO', 3, 'AO-MOX-KCASSAMBA', 'Cassamba', 'cassamba', 'AO-MOX', 1),
  ('AO', 3, 'AO-MOX-KCASSONGO', 'Cassongo', 'cassongo', 'AO-MOX', 1),
  ('AO', 3, 'AO-MOX-KLEUA', 'Léua', 'leua', 'AO-MOX', 1),
  ('AO', 3, 'AO-MOX-KLIANGONGO', 'Liangongo', 'liangongo', 'AO-MOX', 1),
  ('AO', 3, 'AO-MOX-KLUENA', 'Luena', 'luena', 'AO-MOX', 1),
  ('AO', 3, 'AO-MOX-KLUMBALANG', 'Lumbala Nguimbo', 'lumbala nguimbo', 'AO-MOX', 1),
  ('AO', 3, 'AO-MOX-KLUTEMBO', 'Lutembo', 'lutembo', 'AO-MOX', 1),
  ('AO', 3, 'AO-MOX-KLUVUEI', 'Luvuei', 'luvuei', 'AO-MOX', 1),
  ('AO', 3, 'AO-MOX-KMUIE', 'Muié', 'muie', 'AO-MOX', 1),
  ('AO', 3, 'AO-MOX-KMUSSUMAMI', 'Mussuma Mitete', 'mussuma mitete', 'AO-MOX', 1),
  ('AO', 3, 'AO-MOX-KSESSA', 'Sessa', 'sessa', 'AO-MOX', 1),
  ('AO', 3, 'AO-MXL-KCALUNDA', 'Calunda', 'calunda', 'AO-MXL', 1),
  ('AO', 3, 'AO-MXL-KCAZOMBO', 'Cazombo', 'cazombo', 'AO-MXL', 1),
  ('AO', 3, 'AO-MXL-KLUMBALACA', 'Lumbala Caquengue', 'lumbala caquengue', 'AO-MXL', 1),
  ('AO', 3, 'AO-MXL-KMACONDO', 'Macondo', 'macondo', 'AO-MXL', 1),
  ('AO', 3, 'AO-NAM-KBENTIABA', 'Bentiaba', 'bentiaba', 'AO-NAM', 1),
  ('AO', 3, 'AO-NAM-KBIBALA', 'Bibala', 'bibala', 'AO-NAM', 1),
  ('AO', 3, 'AO-NAM-KCAINDE', 'Cainde', 'cainde', 'AO-NAM', 1),
  ('AO', 3, 'AO-NAM-KCAITOU', 'Caitou', 'caitou', 'AO-NAM', 1),
  ('AO', 3, 'AO-NAM-KCAMUCUIO', 'Camucuio', 'camucuio', 'AO-NAM', 1),
  ('AO', 3, 'AO-NAM-KCAPANGOMB', 'Capangombe', 'capangombe', 'AO-NAM', 1),
  ('AO', 3, 'AO-NAM-KCHINGO', 'Chingo', 'chingo', 'AO-NAM', 1),
  ('AO', 3, 'AO-NAM-KLOLA', 'Lola', 'lola', 'AO-NAM', 1),
  ('AO', 3, 'AO-NAM-KLUCIRA', 'Lucira', 'lucira', 'AO-NAM', 1),
  ('AO', 3, 'AO-NAM-KMAMUE', 'Mamué', 'mamue', 'AO-NAM', 1),
  ('AO', 3, 'AO-NAM-KVIREI', 'Virei', 'virei', 'AO-NAM', 1),
  ('AO', 3, 'AO-UIG-KALDEIAVIC', 'Aldeia Viçosa', 'aldeia vicosa', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KALFANDEGA', 'Alfândega', 'alfandega', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KALTOZAZA', 'Alto Zaza', 'alto zaza', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KBEMBE', 'Bembe', 'bembe', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KBENGO', 'Bengo', 'bengo', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KBEU', 'Béu', 'beu', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KBUENGASUL', 'Buenga - Sul', 'buenga - sul', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KCAIONGO', 'Caiongo', 'caiongo', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KCAMATAMBO', 'Camatambo', 'camatambo', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KCAMBAMBA', 'Cambamba', 'cambamba', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KCANCUNGO', 'Cancungo', 'cancungo', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KCANGOLA', 'Cangola', 'cangola', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KCASSECHE', 'Casseche', 'casseche', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KCUANGOCAL', 'Cuango Calumbo', 'cuango calumbo', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KCUILOCAMB', 'Cuilo Camboso', 'cuilo camboso', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KCUILOFUTA', 'Cuilo Futa', 'cuilo futa', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KCUILOPOMB', 'Cuilo Pombo', 'cuilo pombo', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KDAMBA', 'Damba', 'damba', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KDIMUCA', 'Dimuca', 'dimuca', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KICOCA', 'Icoca', 'icoca', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KLEMBOA', 'Lêmboa', 'lemboa', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KLUANGA', 'Luanga', 'luanga', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KMABAIA', 'Mabaia', 'mabaia', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KMACOCOLA', 'Macocola', 'macocola', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KMACOLO', 'Macolo', 'macolo', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KMAQUELADO', 'Maquela do Zombo', 'maquela do zombo', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KMASSAU', 'Massau', 'massau', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KMILUNGA', 'Milunga', 'milunga', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KMUCABA', 'Mucaba', 'mucaba', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KNEGAGE', 'Negage', 'negage', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KNOVAESPER', 'Nova Esperança', 'nova esperanca', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KPETECUSSO', 'Petecusso', 'petecusso', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KQUIBOCOLO', 'Quibocolo', 'quibocolo', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KQUIMBELE', 'Quimbele', 'quimbele', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KQUISSEQUE', 'Quisseque', 'quisseque', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KQUITEXE', 'Quitexe', 'quitexe', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KQUIVUENGA', 'Quivuenga', 'quivuenga', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KSACANDICA', 'Sacandica', 'sacandica', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KSANZAPOMB', 'Sanza Pombo', 'sanza pombo', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KSONGO', 'Songo', 'songo', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KUAMBA', 'Uamba', 'uamba', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KUANDOMUCA', 'Uando Mucaba', 'uando mucaba', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KUIGE', 'Uíge', 'uige', 'AO-UIG', 1),
  ('AO', 3, 'AO-UIG-KVISTAALEG', 'Vista Alegre', 'vista alegre', 'AO-UIG', 1),
  ('AO', 3, 'AO-ZAI-KBUELA', 'Buela', 'buela', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KCALUCA', 'Caluca', 'caluca', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KCUIMBA', 'Cuimba', 'cuimba', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KLUFICO', 'Lufico', 'lufico', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KLUVACA', 'Luvaca', 'luvaca', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KMADIMBA', 'Madimba', 'madimba', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KMBANZAKON', 'Mbanza Kongo', 'mbanza kongo', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KMPALA', 'Mpala', 'mpala', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KMUSSERRA', 'Musserra', 'musserra', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KNZETO', 'Nzeto', 'nzeto', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KPEDRADEFE', 'Pedra de Feitiço', 'pedra de feitico', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KQUIBALANO', 'Quibala - Norte', 'quibala - norte', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KQUIENDE', 'Quiende', 'quiende', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KQUINDEJE', 'Quindeje', 'quindeje', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KQUINSIMBA', 'Quinsimba', 'quinsimba', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KQUINZAU', 'Quinzau', 'quinzau', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KSOYO', 'Soyo', 'soyo', 'AO-ZAI', 1),
  ('AO', 3, 'AO-ZAI-KTOMBOCO', 'Tomboco', 'tomboco', 'AO-ZAI', 1)
on conflict (code) do update set name=excluded.name, name_norm=excluded.name_norm, parent_code=excluded.parent_code, parent_level=excluded.parent_level;